#!/usr/bin/env python3
"""
The Shadow Persuasion Vault — 250 techniques data.
Each technique: num, name, category, risk, use_when, domains, how, deploy, counter.
Organized into 10 parts of 25 techniques each.
"""

PARTS = [
    {
        "num": 1,
        "title": "OPENERS & DETECTOR DISABLERS",
        "subtitle": "The first 30 seconds decide the rest of the conversation.",
        "techniques": [
            {
                "name": "Cold Open",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You need to bypass the normal gatekeeping that kicks in when someone senses they're about to be pitched.",
                "domains": "sales, dating, cold outreach, networking, reconciliation",
                "how": "Open with something that has zero connection to what you actually want. A detail about their environment, a shared observation, a confession. The brain's persuasion alarm only fires when the opening is transactional. Non-transactional openings don't trigger it.",
                "deploy": "At a cousin's wedding after seven years of silence, reader Elena opened with a comment about her father's tie pattern, not the estrangement. Twenty minutes in, he brought up the fight himself.",
                "counter": "A stranger opening with specific, unexpected detail about you is trying to install trust before an ask. Enjoy the conversation, decline the ask.",
            },
            {
                "name": "Low-Status Opening",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You're about to walk into a room where the other person expects you to perform dominance or expertise.",
                "domains": "negotiation, job interviews, sales, family conflict",
                "how": "Open slightly below the status position they expect. Admit you've been reading up on something. Mention a mistake you made last time. Elite negotiators use this because confidence-performance fires the detector instantly. Mild self-deprecation disables it.",
                "deploy": "At the start of a $400K salary negotiation: \"Before we get into numbers, I want to flag that I've been told I'm too direct in these things, so if I come across blunt, it's not intentional.\" The other side immediately relaxes.",
                "counter": "Elite negotiators often lead with humility. Don't mistake it for weakness — it's a frame-setting move.",
            },
            {
                "name": "The Accusation Audit",
                "category": "Opener",
                "risk": "Medium",
                "use_when": "You know the other side is about to lead with a complaint, objection, or grievance.",
                "domains": "customer service, partnership conflicts, sales, family, legal",
                "how": "Say the worst thing they're thinking about you before they say it. The moment you name an accusation yourself, it loses its power as a weapon. Chris Voss's FBI training built a career on this single move.",
                "deploy": "Opening a meeting with a skeptical client: \"You probably think we overpromised last quarter. You're probably wondering if this quarter will be the same. And you probably almost didn't take this call.\" They relax and the real conversation starts.",
                "counter": "If someone opens by naming your likely objections, they've prepared. Slow down before agreeing to anything.",
            },
            {
                "name": "Unrelated Reference Open",
                "category": "Opener",
                "risk": "Low",
                "use_when": "The other person is expecting you to get straight to business, and you want to buy yourself three minutes of real conversation first.",
                "domains": "sales, networking, dating, family, new manager conversations",
                "how": "Reference something genuinely specific and unrelated to your agenda. A book on their shelf. A team they mentioned. A restaurant you both know. The specificity signals you did real research. The irrelevance signals you're not there to pitch.",
                "deploy": "First call with a new CTO: \"Before we start, I noticed in your LinkedIn that you were at Riot in 2018. I was curious if the collapse of the LoL championship format actually affected morale that year.\" You get a real answer. Now you're a human, not a vendor.",
                "counter": "Highly specific unrelated references from new contacts are a pre-frame. Nothing wrong with that, but recognize what it is.",
            },
            {
                "name": "Pre-Frame Drop",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You need to set an expectation or assumption before the real conversation starts, so it's in their head as baseline.",
                "domains": "sales, pitches, difficult conversations, dating",
                "how": "Mention the frame casually in the first 60 seconds. \"I'm only going to take 12 minutes.\" \"This is genuinely informal.\" \"I don't know if we'll be a fit.\" The frame becomes the container the conversation sits inside.",
                "deploy": "Calling a prospect: \"Before I take any of your time, I want to be upfront that this might not be a fit for you. Want me to ask two questions first?\" The defensive posture drops immediately.",
                "counter": "When someone front-loads a disarming frame, they've chosen it intentionally. Track what the frame assumes you've already agreed to.",
            },
            {
                "name": "The Humility Anchor",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You're walking into a room with people who are senior, older, or higher-status than you and you don't want to fake peer energy.",
                "domains": "meetings with execs, dating up, family elders, new clients",
                "how": "Explicitly name their seniority or experience as the reason you wanted to be there. Not as flattery. As positioning. This frees you from performing and grants you the room's permission to ask basic questions.",
                "deploy": "Opening a board meeting as a new exec: \"I want to acknowledge that four of you have been at this longer than I've been alive in this industry, so I'm going to ask questions that probably sound naive. I'd rather ask them than guess.\" You just earned the right to everything.",
                "counter": "When someone invokes your seniority, they're buying room to challenge you. Fine — just notice it.",
            },
            {
                "name": "The Question Hook",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You're cold-calling, cold-emailing, or approaching someone who will immediately try to categorize you as 'salesperson' or 'pest'.",
                "domains": "sales, networking, media pitches, reconnection",
                "how": "Open with a specific question that can only be answered from their perspective. Not a rhetorical one. A real one. The brain can't easily screen out a genuine question from someone who did their homework.",
                "deploy": "Email subject line: \"Quick question about how you handled the 2023 pricing change.\" Open rate 3-5x the industry baseline. Works because the recipient reads the subject and their brain opens a real loop, not a sales loop.",
                "counter": "Specific, researched questions from strangers are almost always a lead-in. Still worth answering if the question is good — just expect the ask.",
            },
            {
                "name": "The Third-Party Pivot",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You've been introduced or referred by someone and you want to lean on that warmth without sounding transactional.",
                "domains": "warm intros, family dynamics, sales, fundraising",
                "how": "Make the third party central for the first 30-60 seconds. Ask about their relationship. Share something the third party told you. The conversation starts as a three-way trust relay, not a two-way sales transaction.",
                "deploy": "Warm intro from David: \"Before anything else, how do you know David? He described you as the one person who knew what the org needed.\" You've now transferred David's trust to yourself.",
                "counter": "If someone lingers on the third party, they're using transferred trust. Check whether you'd actually hire them without the referral.",
            },
            {
                "name": "Specific Compliment",
                "category": "Opener",
                "risk": "Low",
                "use_when": "Generic flattery would fire the detector instantly, but you need to open on a positive note.",
                "domains": "networking, sales, dating, reviews, team management",
                "how": "Compliment something small, specific, and recent. Not their 'whole career.' A particular decision. A line from a recent talk. A specific design choice. Specificity is the difference between flattery and attention.",
                "deploy": "\"I noticed you pushed back on the quarterly timeline in Thursday's all-hands. That was the first time anyone said the quiet part out loud in six months.\" They were being watched; it felt good.",
                "counter": "Specific compliments trigger real attention. Enjoy the recognition, but don't let it accelerate the decision.",
            },
            {
                "name": "Environmental Comment",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You're in a physical or digital space together and need a zero-risk opening that establishes you're both human.",
                "domains": "in-person meetings, video calls, dating, networking",
                "how": "Comment on something in the shared environment. The weather, the office art, a book on the shelf, background noise on their end. The brain categorizes environmental comments as social not transactional.",
                "deploy": "On a Zoom call: \"That's a great bookshelf. Is that a first edition Cialdini behind you?\" You're now the person who noticed their bookshelf. Not the person who's about to pitch them.",
                "counter": "Innocent. Enjoy the conversation.",
            },
            {
                "name": "Shared Inconvenience",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You want instant bonding without performing it.",
                "domains": "networking events, airports, any chance encounter, new client kickoffs",
                "how": "Reference something slightly annoying you're both experiencing. The complicated coffee machine. The bad hotel WiFi. The parking. Shared minor suffering creates micro-alliance faster than any affirmative rapport move.",
                "deploy": "Conference coffee line: \"This is the third time I've tried to figure out which button makes espresso.\" The other person laughs and suddenly you've been talking for 12 minutes.",
                "counter": "Nothing to defend. It's a gift of a social micro-alliance.",
            },
            {
                "name": "Micro-Disclosure",
                "category": "Opener",
                "risk": "Medium",
                "use_when": "You need to accelerate trust in a compressed window and you can't afford the normal multi-meeting trust build.",
                "domains": "sales, partnership talks, custody mediation, dating",
                "how": "Share one small true thing about yourself that has a slight risk attached. Not a confession. Not oversharing. A real opinion you might lose points for. The controlled vulnerability bypasses normal trust-testing.",
                "deploy": "Sales call: \"I'll be honest, I almost didn't reach out. Your LinkedIn headline had enough buzzwords that I assumed you wouldn't take a blunt conversation. I'm here anyway.\" They laugh. The call just became a real one.",
                "counter": "Micro-disclosures are installed, not spontaneous. They work because they're engineered. Don't over-credit.",
            },
            {
                "name": "The Expected Decline",
                "category": "Opener",
                "risk": "Medium",
                "use_when": "You're about to propose something that might get a reflexive 'no' and you want to neutralize that reflex.",
                "domains": "sales, dating asks, raises, upgrades",
                "how": "Preempt the decline yourself. \"I'm almost certainly going to get a no on this.\" The brain can't reflexively reject a proposal that's already been rejected on its behalf. So it actually considers it.",
                "deploy": "Asking for a budget approval: \"I know the answer to this is probably no, but I'd rather ask and hear why than guess.\" The budget holder now has to explain the no, which often means they rethink it.",
                "counter": "When someone opens with 'the answer is probably no,' they're hoping for yes. Evaluate the ask itself, not the framing.",
            },
            {
                "name": "False Start",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You're about to say something that might sound blunt and you want to signal that you're about to be real.",
                "domains": "difficult conversations, feedback, family, management",
                "how": "Start a sentence, stop it, reset. \"Let me... actually, let me start over.\" The false start signals care about precision. The listener braces for signal, not scripted noise.",
                "deploy": "Giving hard feedback to a direct report: \"Let me... actually no, the best way to say this is: the deck you sent isn't good enough for Thursday. Here's why.\" The false start earned you the right to be blunt.",
                "counter": "False starts can be genuine or performed. Either way, lean in — the next sentence is usually the real one.",
            },
            {
                "name": "The Pause Before the Ask",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You're about to ask for something and you want the ask to land with weight.",
                "domains": "any important request",
                "how": "Before the ask, pause for 3-4 full seconds. Not mid-sentence. Just before you make it. The pause flags that what's coming matters. The listener shifts into attention mode.",
                "deploy": "Asking for a promotion: after the context setup, let 4 seconds of silence sit before \"so I'd like to talk about what the path to director looks like in the next two quarters.\" The pause made it unskippable.",
                "counter": "When someone pauses before an ask, they're loading meaning. Don't answer immediately. Let your own pause match theirs.",
            },
            {
                "name": "Permission Frame",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You need to talk about something sensitive and you want the other person in the right posture before you start.",
                "domains": "difficult feedback, family conflict, HR, therapy, leadership",
                "how": "Ask permission to bring up the topic before you bring it up. \"Is it okay if we talk about what happened on Thursday?\" The listener grants permission and, having granted it, becomes the co-owner of the conversation.",
                "deploy": "Spouse conversation: \"Is it okay if I bring up something from Saturday?\" They say yes. Now the conversation isn't an ambush. They're a participant.",
                "counter": "When someone asks permission to bring something up, saying no is an option. Use it if you're not ready.",
            },
            {
                "name": "\"Is it a bad time?\"",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You're calling or approaching someone unannounced and you want the opening to feel respectful, not imposing.",
                "domains": "sales calls, impromptu requests, networking",
                "how": "Open with a sincere 'is it a bad time?' The phrase is calibrated exactly because 99% of the time they say 'no, it's fine' and they've now verbally committed to talking to you. You earned the window by offering not to take it.",
                "deploy": "Cold sales call: \"Is now a bad time to talk?\" 85% of the time the answer is some version of 'I have a few minutes.' Note the phrasing — 'bad time?' not 'good time?' The brain defaults to no on bad.",
                "counter": "The question is a pre-commitment device. If you don't have time, say so. 'Now's not great, email me' is fine.",
            },
            {
                "name": "The Weather Bridge",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You're meeting someone in person, on video, or by phone and you need 30-60 seconds of non-transactional warmth.",
                "domains": "any in-person or synchronous conversation",
                "how": "Mention the weather, but specifically and with a small observation attached. 'This is the first morning in Austin that felt like fall.' The specificity makes it feel human. The observation makes it feel real, not rote.",
                "deploy": "Opening a video call in December: \"I just watched someone in my neighborhood put up Christmas lights in a t-shirt. It's 78 degrees here. How's weather where you are?\" It's a free minute of real conversation.",
                "counter": "Innocent opening move. Nothing to defend.",
            },
            {
                "name": "Research Credibility Drop",
                "category": "Opener",
                "risk": "Medium",
                "use_when": "You're meeting someone for the first time and you want them to know you did the work, without sounding like you stalked them.",
                "domains": "sales, consulting, partnership, fundraising",
                "how": "Reference exactly one piece of specific, public, professionally-obtained research about them in the first 90 seconds. Not five. One. The one says 'I respected your time before this meeting.' Five says 'I'm a stalker.'",
                "deploy": "Meeting a new partner: \"I read the Q3 earnings transcript this morning and noticed you flagged the onboarding drop specifically. I want to make sure this meeting is actually useful for that problem.\" The tone of the whole meeting shifts.",
                "counter": "They did homework. That's a baseline professional move. Don't over-credit it.",
            },
            {
                "name": "The Reference Someone Both Know",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You know of a mutual contact and want to ground the conversation in trusted territory.",
                "domains": "networking, sales, reconnection, hiring conversations",
                "how": "Mention the mutual contact in the first 60 seconds, not as social proof (that would fire the detector) but as context. 'I ran into Sarah last week and she mentioned you're working on X.' The name grounds the conversation in a shared trusted node.",
                "deploy": "First conversation: \"I was catching up with Alex last week and he mentioned you were deep in the security audit stuff right now. How's that going?\" Trusted third party + specific topic = instant real conversation.",
                "counter": "Using a mutual contact as a bridge is common. Evaluate the speaker on their own merits.",
            },
            {
                "name": "Apologetic Disarm",
                "category": "Opener",
                "risk": "Medium",
                "use_when": "You're about to interrupt, impose, or take up unexpected time, and you want to convert that friction into goodwill.",
                "domains": "asking for favors, customer support, interrupting a busy person",
                "how": "Apologize up front, specifically, and then immediately pivot to the ask. 'I'm sorry to grab you on a Friday afternoon for this, but I need 90 seconds.' The apology is the toll you pay to get the attention. Specificity of the apology signals awareness.",
                "deploy": "Grabbing your manager at 4:55pm on a Friday: \"I'm sorry — I know the timing on this is the worst possible. 90 seconds, then you go home on time. Can I?\" You get the 90 seconds.",
                "counter": "Apologies + specific time windows are engineered. Grant the window or refuse it cleanly.",
            },
            {
                "name": "The Earned Meeting",
                "category": "Opener",
                "risk": "Low",
                "use_when": "You got the meeting through effort (a referral chain, repeated asks, a specific favor) and you want to acknowledge that without fishing for credit.",
                "domains": "hard-to-get meetings, fundraising, C-suite access",
                "how": "Acknowledge briefly that you know the meeting was earned and not guaranteed. 'Thanks for making room — I know Alex had to push twice for this.' One sentence. Move on. The acknowledgement earns you implicit respect capital.",
                "deploy": "Meeting a hard-to-reach CEO: \"Thanks for this — I know your assistant had to reshuffle to fit me in. I won't waste the time.\" Then straight to business. The acknowledgement alone buys you more latitude.",
                "counter": "Acknowledgement + efficiency usually equals a serious person. Calibrate accordingly.",
            },
            {
                "name": "Reverse Qualifier Opener",
                "category": "Opener",
                "risk": "High",
                "use_when": "You're talking to a sophisticated buyer or decision maker who is used to being chased, and you want to invert the power dynamic in the first 30 seconds.",
                "domains": "enterprise sales, high-ticket services, dating, hiring",
                "how": "Qualify them, not yourself. 'Before I spend your time on what we do, can I ask two questions to see if we're even the right fit?' The brain recognizes the reversal and instantly re-categorizes you as a peer, not a vendor.",
                "deploy": "First enterprise sales call: \"I want to avoid pitching if this isn't a fit. Can I ask two quick questions first?\" They say yes. Now they're answering, not defending. You've taken the frame.",
                "counter": "Reverse qualifiers are a common high-end sales move. It's fine — just answer the questions honestly and assess whether you actually want what they're selling.",
            },
            {
                "name": "\"I'm probably the wrong person but...\"",
                "category": "Opener",
                "risk": "Medium",
                "use_when": "You want to raise an issue or make a suggestion that's slightly outside your role, and you want to be heard without triggering the 'stay in your lane' reaction.",
                "domains": "cross-functional teams, family dynamics, consulting, new hires",
                "how": "Preface your idea with permission-seeking self-deprecation. 'I'm probably the wrong person to bring this up, but...' The listener's brain grants extra latitude because you acknowledged the overreach before making it.",
                "deploy": "New marketing hire raising something to engineering: \"I'm probably the wrong person to bring this up and feel free to tell me to stay in my lane, but the feature we launched Tuesday looks broken to me on mobile.\" They check. It was broken.",
                "counter": "When people pre-apologize for overreach, they usually have a real point. Hear them out.",
            },
            {
                "name": "Opening With Their Concern",
                "category": "Opener",
                "risk": "Medium",
                "use_when": "The other person is walking in with a worry, complaint, or reservation and they expect you to try to neutralize it.",
                "domains": "sales, customer conflict, family, team management",
                "how": "Open by naming their concern as the first thing you want to address. Don't solve it yet. Just name it. The listener's guard drops because you beat them to the thing they were about to raise.",
                "deploy": "Renewal call with a client who's been frustrated: \"Before anything else, I know you were unhappy about the August outage and I want to spend the first five minutes of this call on that, not on renewal.\" They exhale. The call goes differently.",
                "counter": "Leading with the other person's concern is the right move. Be glad they're doing it. Use the moment.",
            },
        ],
    },
]

# (This file will be filled with the remaining 9 parts via append — see
# vault-techniques-parts-2-10.py which extends PARTS.)
