#!/usr/bin/env python3
"""Vault techniques parts 2-5 (techniques 26-125)."""

PARTS_2_5 = [
    {
        "num": 2,
        "title": "RAPPORT WITHOUT RAPPORT",
        "subtitle": "Real trust in under 60 seconds without a single \u201chow was your weekend\u201d.",
        "techniques": [
            {"name": "Mirroring The Last 3 Words", "category": "Rapport", "risk": "Low",
             "use_when": "The other person just said something important and you want them to keep going.",
             "domains": "negotiation, therapy, sales discovery, parenting teens, interviewing",
             "how": "Repeat their last two to three words as a question with a slight upward inflection. The brain treats it as an invitation to expand rather than as a prompt, so you get 2-3x more detail than direct questions produce.",
             "deploy": "Client: \u201cThe timeline slipped because we lost two engineers.\u201d You: \u201cLost two engineers?\u201d They spend the next ninety seconds explaining what actually went wrong.",
             "counter": "Being mirrored feels strangely good because it signals attention. Enjoy it but don\u2019t overshare."},
            {"name": "Parallel Vulnerability", "category": "Rapport", "risk": "Medium",
             "use_when": "Someone shares something slightly uncomfortable and you want to deepen the exchange without oversharing.",
             "domains": "dating, difficult work conversations, family",
             "how": "Match their level of disclosure with one small notch up of your own, but only one. More than that tips into one-upping. Less than that breaks the exchange. The calibration is what creates trust, not the content.",
             "deploy": "They mention a layoff. You mention one tough professional setback, briefly, then return to them. The conversation deepens without switching to your story.",
             "counter": "If someone matches your vulnerability perfectly on demand, they may be trained at this. Doesn\u2019t mean it\u2019s fake; does mean you can pace yourself."},
            {"name": "The Earned Pause", "category": "Rapport", "risk": "Low",
             "use_when": "You just made a meaningful statement and you want it to land.",
             "domains": "management, high-stakes pitches, family conversations",
             "how": "Stop talking for three to four seconds after a point you care about. The silence tells the listener you meant what you said and aren\u2019t desperate to keep talking. In a room where everyone else is filling air, silence reads as status.",
             "deploy": "After telling a board \u201cI don\u2019t think we should ship this quarter,\u201d hold silence for four seconds. Watch the room shift.",
             "counter": "Pauses carry intent. Don\u2019t rush to fill them. Let the other person\u2019s silence mean what they intend it to mean."},
            {"name": "Minimal Encouragers", "category": "Rapport", "risk": "Low",
             "use_when": "Someone is telling you something important and you want them to keep going without steering the story.",
             "domains": "therapy, interviews, discovery, family listening",
             "how": "Use small non-steering acknowledgments: \u201cmm-hmm\u201d, \u201cI see\u201d, \u201cgo on\u201d, a head nod. The brain reads these as permission to continue rather than evaluation. Talkers will give you 3x the information they would to someone peppering them with questions.",
             "deploy": "Sales discovery call: instead of asking three questions in sixty seconds, use \u201cmm-hmm\u201d and nods. The prospect tells you the actual pain without you having to fish.",
             "counter": "When you notice someone only using minimal encouragers, they\u2019re getting you to talk. Ask them a question."},
            {"name": "The Delayed Agreement", "category": "Rapport", "risk": "Medium",
             "use_when": "You agree with what the other person said, but agreeing too fast will feel performative.",
             "domains": "negotiation, family conflict, debates",
             "how": "Let two to three seconds pass before you express agreement, and add a slight qualifier that shows you actually thought about it. Instant agreement reads as sycophancy. Considered agreement reads as real.",
             "deploy": "Partner in a fight makes a fair point. Don\u2019t say \u201cyou\u2019re right\u201d immediately. Pause. \u201cYou\u2019re right about that. I hadn\u2019t seen it from there.\u201d The agreement lands.",
             "counter": "Delayed agreement is a high-trust move. Don\u2019t be suspicious of it; receive it."},
            {"name": "Naming What They Feel", "category": "Rapport", "risk": "Medium",
             "use_when": "The other person is emotional and the emotion is sitting unaddressed in the room.",
             "domains": "customer conflict, parenting, couples, negotiation",
             "how": "Name the emotion without claiming to fix it. \u201cYou seem frustrated.\u201d \u201cThat sounds exhausting.\u201d Voss calls this labeling. The brain defuses when the feeling is acknowledged, even without agreement.",
             "deploy": "Unhappy customer on the phone: \u201cYou sound like you\u2019ve had to explain this three times already.\u201d They exhale. The real conversation starts.",
             "counter": "Being labeled can feel intimate. Notice whether the labeler is following up with an ask."},
            {"name": "The \u201cSo\u201d Bridge", "category": "Rapport", "risk": "Low",
             "use_when": "You need to summarize what someone said and move the conversation forward without interrogating.",
             "domains": "sales, coaching, consulting, management",
             "how": "Start a recap with \u201cso\u2026\u201d followed by their position in your words. It signals you were listening and gives them a chance to correct you. The correction itself is trust-building.",
             "deploy": "\u201cSo the blocker isn\u2019t the budget, it\u2019s that your CFO wants a reference case before signing.\u201d They either confirm or refine. Either way you\u2019re both closer to the real issue.",
             "counter": "A good \u201cso\u201d bridge shows someone is tracking you. Let them. If the summary is wrong, correct cleanly."},
            {"name": "Reflective Summary", "category": "Rapport", "risk": "Low",
             "use_when": "A conversation has wandered and you need to consolidate what\u2019s been said.",
             "domains": "meetings, therapy, negotiation, mediation",
             "how": "Summarize the last ten minutes in thirty seconds, structured around their priorities, not yours. The summary signals that you\u2019re tracking the whole shape of the conversation and builds authority without claiming any.",
             "deploy": "Mid-meeting: \u201cLet me make sure I have the three things you\u2019ve raised: timeline, security review, and the pricing tier. Is that the order of priority?\u201d The meeting snaps into focus.",
             "counter": "Summaries can quietly edit what was said. Double-check that yours match the other person\u2019s version."},
            {"name": "The Quiet Nod", "category": "Rapport", "risk": "Low",
             "use_when": "You want to convey attention and agreement without interrupting.",
             "domains": "all in-person conversations",
             "how": "A slow, small, held nod at the exact moment they make their key point. Not a rapid series of nods (that reads as anxious or fake). One deliberate nod at the right moment does more than a paragraph.",
             "deploy": "In a job interview, when the candidate lands their best line, give one slow nod. They know they were heard and finish strong.",
             "counter": "A deliberate nod is an attention signal. Return it if you agree, hold still if you don\u2019t."},
            {"name": "Their Rhythm, Your Pace", "category": "Rapport", "risk": "Low",
             "use_when": "You\u2019re talking with someone whose energy is very different from your baseline.",
             "domains": "any cross-cultural, cross-personality, cross-department conversation",
             "how": "Match their pace roughly, not precisely. If they talk fast, speed up 20%. If they talk slow, slow down 20%. The partial match registers as attunement. Exact matching reads as mimicry and fires the detector.",
             "deploy": "On a call with a slow-talking Southern CEO, slow your cadence. You\u2019ll be treated as trustworthy rather than frenetic. The deal closes easier.",
             "counter": "Exact matching is a tell. Partial matching is just being present."},
            {"name": "Labeled Respect", "category": "Rapport", "risk": "Low",
             "use_when": "You\u2019re pushing back on someone senior or powerful and need to disagree without disrespecting.",
             "domains": "boardrooms, family elders, senior clients",
             "how": "Name the respect explicitly before the disagreement. \u201cWith respect to what you\u2019ve built here\u2026\u201d The label doesn\u2019t soften the disagreement, it frames the disagreement as coming from someone who values their position.",
             "deploy": "To a founder: \u201cYou built this team from four to forty. With that context in mind, I think the Q4 plan is wrong.\u201d The disagreement lands without costing the relationship.",
             "counter": "Labeled respect is structural, not flattering. Take the respect, then engage the substance."},
            {"name": "The Identified Gap", "category": "Rapport", "risk": "Medium",
             "use_when": "You want to signal you\u2019ve noticed what\u2019s missing from a conversation without being the person who says the awkward thing directly.",
             "domains": "meetings, group dynamics, family, therapy",
             "how": "Gently name what hasn\u2019t been said. \u201cI notice we haven\u2019t talked about X.\u201d The phrase carries low confrontation weight but high signal weight. The omission gets addressed without anyone being attacked.",
             "deploy": "In a postmortem meeting: \u201cWe\u2019ve talked about engineering gaps. We haven\u2019t talked about the PM who pushed the deadline.\u201d The conversation shifts, and you didn\u2019t name names.",
             "counter": "Gap-naming creates pressure. Decide whether to address the gap or ask why they\u2019re raising it."},
            {"name": "Permission to Disagree", "category": "Rapport", "risk": "Low",
             "use_when": "You want the other person to feel safe pushing back, which paradoxically makes them agree more often.",
             "domains": "management, couples, sales",
             "how": "Explicitly offer them space to say no or disagree before you make your point. \u201cTell me if I\u2019m off here\u2026\u201d \u201cPush back on this\u2026\u201d The invitation reduces the social cost of disagreement, and most people, not facing the cost, don\u2019t bother.",
             "deploy": "Pitching a project: \u201cTell me if I\u2019m misreading this, but it feels like you want the scope smaller.\u201d 70% of the time they say \u201cno, you\u2019re reading it right.\u201d",
             "counter": "Invitations to disagree are rarely traps. Take the invitation if you want to."},
            {"name": "Validating Without Agreeing", "category": "Rapport", "risk": "Medium",
             "use_when": "The other person needs to feel heard but you don\u2019t actually agree with what they\u2019re saying.",
             "domains": "customer service, family conflict, therapy, mediation",
             "how": "Validate the legitimacy of their feeling without endorsing the substance. \u201cI can see why that would feel like a betrayal.\u201d You acknowledged the emotion without saying it was a betrayal.",
             "deploy": "Customer: \u201cThis is highway robbery.\u201d You: \u201cI can see why it would feel like that after three price increases in a year.\u201d The conversation continues instead of collapsing.",
             "counter": "Validation without agreement is a professional skill. Be glad when someone uses it on you rather than arguing."},
            {"name": "The Sigh Match", "category": "Rapport", "risk": "Medium",
             "use_when": "The other person sighs or groans and you want to create micro-solidarity.",
             "domains": "any in-person, phone call with affect",
             "how": "When they sigh, sigh back, smaller. Not a performance. A real breath. The parasympathetic match registers as alignment at a pre-verbal level. One of the most underused rapport moves in the canon.",
             "deploy": "Frustrated client on the phone sighs about a slipped deadline. You exhale slightly, audibly. \u201cYeah.\u201d The next sentence they say is softer.",
             "counter": "Performed sighs are detectable. Real ones are contagious. Let yourself match when it\u2019s genuine."},
            {"name": "Energy Match (Not Body Match)", "category": "Rapport", "risk": "Medium",
             "use_when": "You\u2019ve read that you should mirror body language but you\u2019ve noticed people catch it and feel creeped out.",
             "domains": "all in-person",
             "how": "Instead of matching posture or gesture, match their energy level. Their enthusiasm. Their caution. Their humor. The match happens in the register not the body. Undetectable and effective.",
             "deploy": "Meeting with an understated engineer who speaks quietly. Drop your volume to match. The conversation flows twice as long as it would have.",
             "counter": "Body mirroring is visible. Energy matching is almost invisible. Both are being used. The former is amateur; the latter is elite."},
            {"name": "The Question That Flatters", "category": "Rapport", "risk": "Medium",
             "use_when": "You want to signal respect without saying \u201cI respect you,\u201d which lands as flattery.",
             "domains": "management, networking, consulting, sales",
             "how": "Ask a question that only someone who already respects them would ask. \u201cWhen you ran the 2019 restructuring, what do you wish you\u2019d done differently?\u201d It assumes their experience and invites reflection.",
             "deploy": "To a senior leader: \u201cOf all the CEOs you\u2019ve coached, what\u2019s the one mistake you see them repeat?\u201d They feel seen without being complimented. The conversation is suddenly real.",
             "counter": "Flattering questions are fine; they\u2019re just engineered. Answer the ones that interest you, skip the ones that don\u2019t."},
            {"name": "Uncertainty Admission", "category": "Rapport", "risk": "Medium",
             "use_when": "You\u2019re in a meeting where everyone is performing certainty and nobody actually knows.",
             "domains": "strategy meetings, leadership, family decisions",
             "how": "Be the first person to admit you\u2019re not sure. \u201cI genuinely don\u2019t know if this is right.\u201d The room exhales. Others who were performing certainty now feel permission to drop the act. The conversation improves instantly.",
             "deploy": "Strategy offsite where everyone\u2019s nodding at the plan: \u201cHonestly, I don\u2019t know if this works. What am I missing?\u201d The CFO now admits they also don\u2019t. Problem gets solved.",
             "counter": "Someone admitting uncertainty is usually a leader, not a weakness. Lean in."},
            {"name": "The \u201cI Hadn\u2019t Thought About That\u201d", "category": "Rapport", "risk": "Low",
             "use_when": "Someone says something you actually hadn\u2019t considered and you want to acknowledge it properly.",
             "domains": "all",
             "how": "Use the exact phrase. Mean it. Let it sit for two seconds before responding. The listener registers genuine attention. Too many people skip real acknowledgements because they\u2019re already formulating their response.",
             "deploy": "In a design review, a junior raises an edge case you missed. \u201cI hadn\u2019t thought about that.\u201d Pause. \u201cYou\u2019re right.\u201d The junior now trusts you; everyone noticed."},
            {"name": "Calibrated Curiosity", "category": "Rapport", "risk": "Low",
             "use_when": "You want to ask questions that make the other person engage rather than defend.",
             "domains": "discovery, dating, interviewing, consulting",
             "how": "Ask \u201chow\u201d and \u201cwhat\u201d questions, not \u201cwhy.\u201d Why triggers justification. How and what trigger explanation. The difference is the entire temperature of the conversation.",
             "deploy": "Prospect: \u201cWe\u2019re not ready to buy right now.\u201d Don\u2019t say \u201cwhy not.\u201d Say \u201chow will you know when you are?\u201d They answer the real question.",
             "counter": "Good questioners use how/what because they work. Answering is fine; just give the actual answer."},
            {"name": "Name the Elephant", "category": "Rapport", "risk": "High",
             "use_when": "There\u2019s a tension in the room everyone is pretending isn\u2019t there.",
             "domains": "family reunions, team meetings, M&A conversations",
             "how": "Say the thing. \u201cThe obvious thing we\u2019re not talking about is X.\u201d Direct, calm, without accusation. The group exhales because the tension has a name.",
             "deploy": "At a post-acquisition integration meeting: \u201cThe thing nobody\u2019s saying is that five of your people are worried about their jobs. Let\u2019s just address that first.\u201d The room shifts.",
             "counter": "Naming the elephant is a power move. Respect the courage, engage the substance."},
            {"name": "The Shared Observation", "category": "Rapport", "risk": "Low",
             "use_when": "You want to create alignment without making a claim.",
             "domains": "networking, new client kickoffs, parenting together",
             "how": "Point at something external you\u2019re both looking at and offer a small observation. The alignment is immediate because you\u2019re not asking them to agree with you about you \u2014 you\u2019re both agreeing about something outside you.",
             "deploy": "Walking into a portfolio meeting, pointing at a chart: \u201cThat Q2 dip is the interesting story, not the Q4 recovery.\u201d You\u2019ve just become a peer.",
             "counter": "Shared observations are innocuous. Engage or ignore."},
            {"name": "The Un-Mirror", "category": "Rapport", "risk": "High",
             "use_when": "You want to break a pattern someone is running on you without breaking the conversation.",
             "domains": "high-pressure sales, manipulation, family dynamics",
             "how": "Deliberately do the opposite of what they\u2019re doing. If they lean in, lean back. If they speed up, slow down. The pattern-break signals you\u2019re aware and not suggestible. Professional interrogators use this to re-take control.",
             "deploy": "Pushy car salesperson leans in and speeds up. You lean back and pause for five seconds before answering. The pressure deflates.",
             "counter": "Un-mirroring is a competence signal. If someone\u2019s doing it to you, they\u2019re not easy to move."},
            {"name": "Slower Than Them", "category": "Rapport", "risk": "Low",
             "use_when": "The other person is in urgency mode and pulling you into it.",
             "domains": "negotiation, customer service, family conflict",
             "how": "Move slightly slower than they are. Talk slower, answer slower, breathe slower. You\u2019re not stalling. You\u2019re setting tempo. The other person recalibrates to yours rather than the reverse.",
             "deploy": "Customer demanding instant resolution: you slow your speech by 15%. Within two minutes they\u2019ve slowed down too and the real problem surfaces.",
             "counter": "Slower pacing is a dominance move without dominance display. Let them set it if you\u2019re not in a rush."},
            {"name": "Tactical Silence as Rapport", "category": "Rapport", "risk": "Low",
             "use_when": "The other person has just said something real and you want to honor it by not rushing to fill the air.",
             "domains": "all",
             "how": "After a meaningful statement, sit in silence for four to five seconds. Not awkwardly. Peacefully. The silence communicates that you heard them and are considering, not just queueing your response.",
             "deploy": "In a tough feedback conversation, after the person shares something vulnerable, sit for four seconds. Then: \u201cThank you. That took something to say.\u201d",
             "counter": "Held silence is real attention. Let it happen."},
        ],
    },
    {
        "num": 3,
        "title": "MAKING THEM PERSUADE THEMSELVES",
        "subtitle": "People defend conclusions they reached on their own.",
        "techniques": [
            {"name": "The Socratic Cascade", "category": "Influence", "risk": "Medium",
             "use_when": "You need someone to reason through a conclusion rather than hear it from you.",
             "domains": "management, teaching, sales, family",
             "how": "Ask three to five questions in sequence, each one narrowing the logic. By the last question, the answer is obvious to them and they\u2019ve generated it themselves. The conclusion is now theirs to defend.",
             "deploy": "Board member opposed to the new pricing: \u201cWhat\u2019s the churn on the current plan?\u201d \u201cWhat\u2019s the LTV of the new cohort?\u201d \u201cAt what break-even does the new price pay back?\u201d By the fourth question, they\u2019re selling you.",
             "counter": "When someone asks you cascading narrowing questions, they\u2019re walking you to a conclusion. Check whether the conclusion fits your actual situation, not just the logic of the path."},
            {"name": "Leading Question Chain", "category": "Influence", "risk": "Medium",
             "use_when": "You need a series of small yesses that set up a bigger one.",
             "domains": "sales, negotiation, management",
             "how": "Chain three to four questions where the answer is almost certainly yes. The brain builds momentum with each yes. By the fourth, yes is the default state. Now ask the real question.",
             "deploy": "\u201cYou want to grow revenue this quarter, right?\u201d \u201cAnd you\u2019ve noted the team can\u2019t take another tool, right?\u201d \u201cAnd the blocker is really onboarding, right?\u201d \u201cThen let\u2019s spend the budget on onboarding.\u201d",
             "counter": "If you notice you\u2019ve said yes three times, pause before the fourth. Let the momentum reset."},
            {"name": "The Assumed Conclusion", "category": "Influence", "risk": "High",
             "use_when": "You want to move a conversation forward by treating the outcome as already decided.",
             "domains": "sales, negotiation, parenting",
             "how": "Speak as if the decision is made and you\u2019re on to logistics. The brain often goes along rather than fight the assumption. This is the classic \u201cwould you like it in blue or green\u201d move, but done subtly.",
             "deploy": "Sales call: \u201cSo when we kick off in November, what\u2019s your preferred day of the week for check-ins?\u201d 50% of prospects answer.",
             "counter": "Assumed conclusions can be politely refused. \u201cLet me back up \u2014 we haven\u2019t decided to move forward yet.\u201d"},
            {"name": "Their Own Words Returned", "category": "Influence", "risk": "Low",
             "use_when": "They\u2019ve already stated a principle or position and you want to use it without sounding like you\u2019re using it.",
             "domains": "negotiation, management, family",
             "how": "Feed back exactly what they said earlier, verbatim, at a later moment. The phrasing matches their own voice so it doesn\u2019t register as persuasion; it registers as reminder.",
             "deploy": "Earlier they said \u201cwe don\u2019t ship unfinished work.\u201d Later when they\u2019re about to ship unfinished work: \u201cYou told me earlier, we don\u2019t ship unfinished work.\u201d They concede.",
             "counter": "Be precise about what you say in the first part of any important conversation. It\u2019ll be returned to you."},
            {"name": "The Incomplete Thought", "category": "Influence", "risk": "Medium",
             "use_when": "You want them to finish an argument so they own it.",
             "domains": "teaching, sales, coaching, management",
             "how": "Start a sentence, trail off, let them complete it. The brain can\u2019t resist closing an open loop. The completion becomes their position.",
             "deploy": "\u201cAnd if we don\u2019t move on this by Friday, then\u2026\u201d The client finishes: \u201cthen we\u2019ll miss the onboarding window.\u201d Now it\u2019s their framing of the risk.",
             "counter": "If someone trails off, you don\u2019t have to complete. Silence is fine."},
            {"name": "Planting the Objection", "category": "Influence", "risk": "High",
             "use_when": "You know they\u2019ll have a specific objection and you want to defuse it before it hardens.",
             "domains": "sales, pitches, internal politics",
             "how": "Name the objection yourself, casually, in the first third of the conversation. Then answer it. Then move on. When the objection would have surfaced, it\u2019s already processed.",
             "deploy": "Pitching a new tool: \u201cYou might think this just adds to the stack. Actually, it replaces two tools you already pay for.\u201d By objection time, it\u2019s solved."},
            {"name": "The Stakes Question", "category": "Influence", "risk": "Medium",
             "use_when": "Someone is treating a decision as low-stakes when it isn\u2019t.",
             "domains": "management, family, sales, negotiation",
             "how": "Ask them what\u2019s at stake if they\u2019re wrong. The brain has to actually compute it. Most of the time the real stakes were underestimated, and the decision gravity increases.",
             "deploy": "Employee considering quitting impulsively: \u201cIf you\u2019re wrong about the next job being better, what\u2019s the cost of that wrong?\u201d They pause and reconsider."},
            {"name": "\u201cWhat would need to be true\u2026\u201d", "category": "Influence", "risk": "Low",
             "use_when": "Someone is saying no and you want to get to the real condition behind the no.",
             "domains": "sales, partnerships, family, hiring",
             "how": "Ask: \u201cWhat would need to be true for this to be a yes?\u201d The question turns a closed door into a conversation about conditions. 30% of the time they name a condition you can meet.",
             "deploy": "Prospect: \u201cWe\u2019re not buying this quarter.\u201d You: \u201cWhat would need to be true for you to buy next quarter?\u201d They name it. You solve for it."},
            {"name": "Reverse Reasoning Prompt", "category": "Influence", "risk": "Medium",
             "use_when": "You want them to argue for your position by asking them to argue against it.",
             "domains": "teaching, management, strategic conversations",
             "how": "Ask them to steelman the opposite view. The act of building the counter-argument often exposes weaknesses that flip them to your side. This is the classic \u201csteelman your opponent\u201d move weaponized.",
             "deploy": "To a reluctant exec: \u201cMake the strongest case for launching in Q1 \u2014 what would that argument sound like?\u201d They build it. They convince themselves."},
            {"name": "The Hypothetical Commit", "category": "Influence", "risk": "Medium",
             "use_when": "You want a preview of their decision without asking for a real commitment.",
             "domains": "sales, dating, partnerships",
             "how": "\u201cHypothetically, if X were in place, would you move forward?\u201d The brain treats the hypothetical like a real preview. Their answer reveals the actual blocker.",
             "deploy": "\u201cHypothetically, if security approved this today, would you sign?\u201d Answer: \u201cYes.\u201d Now you know security is the only blocker."},
            {"name": "Option Narrowing", "category": "Influence", "risk": "Low",
             "use_when": "They\u2019re stuck in decision paralysis.",
             "domains": "sales, consulting, teaching",
             "how": "Present exactly two options, not three or five. The brain handles binary choices with confidence and freezes on more. Narrow the menu for them.",
             "deploy": "\u201cYou have two paths here: fast launch with a smaller scope, or wait two quarters for the full version. Which one?\u201d They pick."},
            {"name": "The Self-Rejection Setup", "category": "Influence", "risk": "Medium",
             "use_when": "You want someone to eliminate a weak option before you have to argue against it.",
             "domains": "sales, strategy, family",
             "how": "List the weakest option first and describe it neutrally. The brain does the rejection work for you. By the time you name the stronger option, it lands as obvious.",
             "deploy": "\u201cOne path is to do nothing for another quarter. Another is to ship the cut-down version now.\u201d They reject option one themselves."},
            {"name": "Elimination Sequence", "category": "Influence", "risk": "Low",
             "use_when": "Five options feel like too many and the conversation is stalling.",
             "domains": "strategy, product, family decisions",
             "how": "Ask them which option is clearly wrong, first. Then the next one. By the third elimination you\u2019re down to the right answer, and they chose it.",
             "deploy": "Five hiring candidates: \u201cWho\u2019s clearly not right?\u201d \u201cWho\u2019s also not right?\u201d By option three you\u2019re left with two and the decision is easy."},
            {"name": "The Time-Frame Question", "category": "Influence", "risk": "Low",
             "use_when": "You need to turn an abstract \u201csomeday\u201d into a concrete \u201cby when.\u201d",
             "domains": "sales, management, project planning",
             "how": "Ask when something needs to be true by. The answer forces specificity and creates the pressure to move.",
             "deploy": "\u201cWhen do you need to have this in place by?\u201d \u201cEnd of March.\u201d Now there\u2019s a deadline. Decisions flow from it."},
            {"name": "Consequence Walkthrough", "category": "Influence", "risk": "Medium",
             "use_when": "Someone is underweighting the downside of inaction.",
             "domains": "sales, management, family",
             "how": "Walk them through the specific cascade of what happens if nothing changes. Not the \u201cyou\u2019ll regret it\u201d version. The specific version. \u201cYou\u2019ll have the same meeting in six months, with the same agenda, and still no decision.\u201d",
             "deploy": "To a delayed buyer: \u201cIf we don\u2019t start in October, onboarding hits the holidays, usage drops 40%, and you\u2019re reporting weak Q1 numbers.\u201d They decide."},
            {"name": "The \u201cIf You Were Me\u201d", "category": "Influence", "risk": "Medium",
             "use_when": "You\u2019re stuck in a negotiation or decision and you want to use their perspective.",
             "domains": "negotiation, partnership, family",
             "how": "\u201cIf you were me, what would you do?\u201d Forces them out of their position and into yours. The answer usually reveals a creative solution neither of you would have found in adversarial mode.",
             "deploy": "Negotiating a partnership that\u2019s stuck: \u201cIf you were me, how would you make this work?\u201d They propose a structure that works."},
            {"name": "Reversal Prediction", "category": "Influence", "risk": "Medium",
             "use_when": "You expect them to reverse later and you want to lock them in now.",
             "domains": "sales, commitments, internal politics",
             "how": "Predict the reversal out loud. \u201cA month from now, you might look at this and think it was too aggressive.\u201d Naming it reduces the social cost of sticking with the original decision.",
             "deploy": "After a hiring decision: \u201cAt some point you\u2019ll wonder if this was the right hire. That\u2019s normal. Check back after ninety days.\u201d They stay committed through the doubt."},
            {"name": "Authored Scenarios", "category": "Influence", "risk": "Medium",
             "use_when": "You need someone to see the future you\u2019re proposing in concrete terms.",
             "domains": "sales, leadership, family decisions",
             "how": "Describe the future in specific daily detail. Not \u201cyou\u2019ll be more efficient.\u201d \u201cOn a Tuesday in March you\u2019ll run the weekly and the dashboard is already there.\u201d The specificity makes it real.",
             "deploy": "Pitching a dashboard product: \u201cMonday 9am stand-up, you open the screen, the numbers are already there, the meeting ends in 15 minutes.\u201d They see it. They buy."},
            {"name": "The Guided Calculation", "category": "Influence", "risk": "Low",
             "use_when": "The numbers matter and you want them to run them rather than hearing them from you.",
             "domains": "sales, negotiation, financial decisions",
             "how": "Walk them through the math one step at a time, asking them to confirm each one. By the end they\u2019ve done the calculation and they own the result.",
             "deploy": "\u201cYou have 200 reps. Each one loses 3 hours a week on this. That\u2019s 600 hours. At $75 an hour that\u2019s\u2026\u201d They finish: \u201c$45K a week.\u201d Decision made."},
            {"name": "Micro-Yes Chain", "category": "Influence", "risk": "Medium",
             "use_when": "You want to build agreement momentum.",
             "domains": "sales, dating, management",
             "how": "A gentler cousin of the Leading Question Chain \u2014 ask three to four low-stakes things they\u2019d obviously agree with. Each yes makes the next easier.",
             "deploy": "Sales conversation: \u201cMakes sense?\u201d \u201cReasonable?\u201d \u201cWorth a conversation?\u201d \u201cYes.\u201d The big ask lands on the fourth yes."},
            {"name": "The Embedded Assumption", "category": "Influence", "risk": "High",
             "use_when": "You want a premise accepted without defending it.",
             "domains": "sales, politics, negotiation",
             "how": "Build the assumption into a question rather than stating it. \u201cWhen we launch, what day do you want to go live?\u201d The assumption (we\u2019re launching) becomes accepted by virtue of being embedded in a later question.",
             "deploy": "\u201cWhen we kick off, should we do the internal announcement on a Tuesday or a Thursday?\u201d They pick a day. They\u2019ve accepted the kickoff.",
             "counter": "Watch for questions that bake in a premise. It\u2019s a standard move. You can extract the premise and ask whether you actually agree to it."},
            {"name": "Future-Paced Question", "category": "Influence", "risk": "Medium",
             "use_when": "You want them to mentally live in the outcome before committing.",
             "domains": "sales, dating, career decisions",
             "how": "Ask them to imagine themselves in the future after the decision. \u201cA year from now, if this is working, what do you see?\u201d They describe it. Now they want it.",
             "deploy": "Coaching call: \u201cA year from now, if this year goes well, what changes at home?\u201d They describe the promotion, the move, the relief. They commit."},
            {"name": "The Identity Ladder", "category": "Influence", "risk": "High",
             "use_when": "The decision requires them to become a slightly different version of themselves.",
             "domains": "leadership, therapy, major life choices",
             "how": "Frame the decision as consistent with the identity they already claim. \u201cPeople who are serious about X do Y.\u201d The brain protects its self-image. Hanging the decision on identity makes the decision feel like coherence, not change.",
             "deploy": "Engineer considering a manager role: \u201cEngineers who want to stop being interrupted by decisions they can\u2019t influence take the manager role.\u201d They take it."},
            {"name": "Past-Success Reminder", "category": "Influence", "risk": "Low",
             "use_when": "They\u2019re hesitant to commit and you want to remind them of their own competence.",
             "domains": "coaching, management, sales",
             "how": "Reference a prior moment when they did the hard thing and it worked. Specifically. Briefly. Then pivot.",
             "deploy": "Client delaying a hard decision: \u201cRemember in 2022 when you fired the VP and the whole team rebuilt? You weren\u2019t sure. It worked.\u201d They move."},
            {"name": "Self-Diagnosis Prompt", "category": "Influence", "risk": "Low",
             "use_when": "You want them to identify their own problem rather than hear you name it.",
             "domains": "management, consulting, therapy",
             "how": "Ask: \u201cWhat do you think is the real issue here?\u201d Most people can diagnose their own situation once given space. The diagnosis, being theirs, is defensible.",
             "deploy": "Underperforming report: \u201cIf you had to name the real problem, what would you say?\u201d They name it. Now you can solve it together."},
        ],
    },
    {
        "num": 4,
        "title": "SILENCE, PAUSES, AND TIMING",
        "subtitle": "The most underused weapons in the entire influence canon.",
        "techniques": [
            {"name": "The 4-Second Pause", "category": "Timing", "risk": "Low",
             "use_when": "You\u2019ve said something important and you want it to sit.",
             "domains": "all",
             "how": "Count to four in your head after making a point. Four seconds feels like an eternity in most conversations but lands as deliberate, not awkward. It signals confidence and invites response.",
             "deploy": "After naming your salary number, count to four. The other side usually either accepts or counters lower than they planned because the silence pressures them."},
            {"name": "The 11-Second Silence", "category": "Timing", "risk": "High",
             "use_when": "You\u2019re in a negotiation and the other side has just made an unacceptable offer.",
             "domains": "negotiation, sales, high-stakes purchase",
             "how": "Say nothing for eleven seconds. Eleven is the magic number \u2014 long enough to be uncomfortable, short enough to still be within professional bounds. The other side will usually break first and improve their offer.",
             "deploy": "Contractor quotes $13,500. You say nothing. At second 9 he starts explaining. At second 11 he says \u201cI could probably do it for $2,500.\u201d True story from the book."},
            {"name": "Delayed Response", "category": "Timing", "risk": "Low",
             "use_when": "Someone has asked you a question that expects a fast answer.",
             "domains": "management, negotiation, high-pressure conversations",
             "how": "Let two to three seconds pass before you answer. Not dramatic. Just deliberate. The delay removes the illusion of a rushed answer and increases the weight of what you say.",
             "deploy": "\u201cWhen can you have this done?\u201d Delay two seconds. \u201cMonday.\u201d The Monday feels more credible than if you\u2019d said it instantly."},
            {"name": "The Interrupted Pause", "category": "Timing", "risk": "Medium",
             "use_when": "You\u2019re about to be cut off mid-pause and you want to protect the silence.",
             "domains": "negotiation, management",
             "how": "If someone tries to fill your pause, raise one finger, or say \u201chold on,\u201d gently. The interruption recovery makes it clear the silence was intentional and earns you three to five more seconds.",
             "deploy": "Mid-pause in a salary talk, counterpart starts to speak. You: \u201cHold on \u2014 let me think.\u201d Silence extends. You gain weight."},
            {"name": "Counting Before Replying", "category": "Timing", "risk": "Low",
             "use_when": "You\u2019re emotional and about to say something you\u2019ll regret.",
             "domains": "family, management, personal",
             "how": "Count silently to five before you respond. The count slows the heart rate enough to unhook from the amygdala response. Nobody notices the pause but your nervous system does."},
            {"name": "The Question Hang", "category": "Timing", "risk": "Medium",
             "use_when": "You\u2019ve asked a question and they\u2019re struggling to answer.",
             "domains": "therapy, management, negotiation",
             "how": "Don\u2019t rescue them. Let the question hang. The struggle to answer usually produces a more honest answer than the easy answer would have.",
             "deploy": "\u201cWhy did you take this job?\u201d Silence. Fifteen seconds. Then: \u201cHonestly? I was scared.\u201d That answer wouldn\u2019t have come if you\u2019d rescued them."},
            {"name": "Rhetorical Silence", "category": "Timing", "risk": "Medium",
             "use_when": "You want to make a point without saying anything.",
             "domains": "meetings, family, negotiation",
             "how": "When someone says something egregious, say nothing. The lack of response is itself a response. The listener recalibrates.",
             "deploy": "Employee says something questionable in a 1:1. You don\u2019t respond. Fifteen seconds. They self-correct."},
            {"name": "Pre-Answer Sigh", "category": "Timing", "risk": "Medium",
             "use_when": "You need to signal reluctance or difficulty before answering.",
             "domains": "negotiation, family, service professions",
             "how": "Sigh audibly before answering. The sigh pre-frames your answer as considered and slightly reluctant. It makes concessions feel more valuable and refusals feel more considered.",
             "deploy": "Boss asks you to work the weekend. Sigh. \u201cI can move things around this time.\u201d The sigh made the yes cost something."},
            {"name": "The \u201cHmm\u201d Pause", "category": "Timing", "risk": "Low",
             "use_when": "You want to signal active thought without stalling.",
             "domains": "all",
             "how": "Use a short, real \u201chmm\u201d before responding. It\u2019s a pace-setter. It earns you two to three extra seconds without seeming like you\u2019re stalling."},
            {"name": "The Stretch Pause", "category": "Timing", "risk": "Medium",
             "use_when": "A decision is being rushed and you want to slow it deliberately.",
             "domains": "high-pressure sales, family decisions",
             "how": "Physically lean back, breathe out, and let the silence stretch. The body language reads as \u201cI\u2019m not going to be rushed.\u201d The other side recalibrates pace.",
             "deploy": "Pushy salesperson: you lean back, slow your breathing. \u201cLet me think about this.\u201d The close collapses."},
            {"name": "Audio Rewind", "category": "Timing", "risk": "Medium",
             "use_when": "Someone has just said something important and you want them to say it again more carefully.",
             "domains": "negotiation, discovery",
             "how": "Pause, then say: \u201cSorry, can you say that again?\u201d with genuine attention. The second time they phrase it, it\u2019ll be sharper. Both versions now exist in their head. The second is what they meant."},
            {"name": "The Cold Start", "category": "Timing", "risk": "Low",
             "use_when": "You\u2019re opening a meeting where people expect small talk.",
             "domains": "all meetings",
             "how": "Skip the small talk. Start with the substance. The break in expected pattern signals focus and value of time."},
            {"name": "Deliberate Slowness", "category": "Timing", "risk": "Low",
             "use_when": "You\u2019re being pulled into someone else\u2019s urgency and it\u2019s not your urgency.",
             "domains": "service work, family crises, management",
             "how": "Deliberately do everything slower than they expect. Walk slower. Talk slower. Type slower. The tempo communicates: I\u2019m not in your crisis. The other person\u2019s crisis usually de-escalates when it doesn\u2019t have an accomplice."},
            {"name": "Timing the Ask", "category": "Timing", "risk": "High",
             "use_when": "You have one shot at a big ask and you need the moment to be right.",
             "domains": "raises, proposals, high-stakes favors",
             "how": "Wait for the moment when they\u2019re in flow, not stressed, not distracted, and slightly in your debt from a recent win. The ask lands 3x better with right timing than with perfect phrasing at bad timing."},
            {"name": "The Meeting-End Ask", "category": "Timing", "risk": "Medium",
             "use_when": "You want a micro-commitment and the meeting is wrapping.",
             "domains": "sales, management",
             "how": "Ask in the last 60 seconds, after they\u2019ve already checked out mentally. Low-stakes asks get higher yes rates at the end of meetings because the cost of defending a no isn\u2019t worth it."},
            {"name": "Email Timing Leverage", "category": "Timing", "risk": "Low",
             "use_when": "You\u2019re sending an email that you want read and acted on.",
             "domains": "all email",
             "how": "Send between 6:45am and 7:15am on a Tuesday or Thursday. Opens 2-3x higher than 10am. The inbox is emptier and your email floats at the top until they start the day."},
            {"name": "The Friday 4pm Send", "category": "Timing", "risk": "High",
             "use_when": "You need to deliver difficult news and minimize immediate pushback.",
             "domains": "management, HR, difficult updates",
             "how": "Send late Friday afternoon. The recipient processes over the weekend, so by Monday their first reaction has already cooled. Used carefully \u2014 this is a specific tool, not a default.",
             "counter": "If you get a Friday afternoon email from someone delivering bad news, note the timing. Take the weekend before responding."},
            {"name": "Phone Call Over Email", "category": "Timing", "risk": "Medium",
             "use_when": "The email thread has gotten tense or the conversation is stuck.",
             "domains": "all",
             "how": "Switch to phone deliberately. Tone, pause, and response-time controls are all better on phone. Most stuck email threads unstick in a three-minute call."},
            {"name": "The Walkback Pause", "category": "Timing", "risk": "Medium",
             "use_when": "You just said something you want to soften without erasing.",
             "domains": "management, family, negotiation",
             "how": "Pause. Let it sit. Then: \u201cLet me say that a different way.\u201d The pause signals the walkback is thoughtful, not panicked."},
            {"name": "Strategic Yawn", "category": "Timing", "risk": "High",
             "use_when": "You\u2019re negotiating and you want to signal you\u2019re not invested.",
             "domains": "negotiation, high-end sales",
             "how": "A single, real yawn mid-negotiation signals \u201cthis isn\u2019t life-or-death for me.\u201d The other side often improves the offer to re-engage you. Use sparingly; if detected as performance, it\u2019s very costly."},
            {"name": "Deliberate Breath Match", "category": "Timing", "risk": "Low",
             "use_when": "You want to de-escalate someone who\u2019s physically activated.",
             "domains": "therapy, family, customer service",
             "how": "Slow your own breath to about 60% of their rate. After 60-90 seconds their nervous system often mirrors yours and calms. No verbal content required."},
            {"name": "The Tactical \u201cI Need a Minute\u201d", "category": "Timing", "risk": "Low",
             "use_when": "You\u2019re about to be rushed into a decision.",
             "domains": "sales, family, negotiation",
             "how": "\u201cI need a minute.\u201d Say it flat. Then leave the room or go quiet. The rush collapses. Most important decisions get made worse by the rush, better by the minute."},
            {"name": "Calendar Space", "category": "Timing", "risk": "Low",
             "use_when": "Someone asks to meet immediately and it doesn\u2019t need to be immediate.",
             "domains": "sales, management",
             "how": "Offer a slot three to five days out. Availability signals status. Too-quick availability signals you\u2019re desperate for the meeting."},
            {"name": "Non-Response Window", "category": "Timing", "risk": "High",
             "use_when": "You\u2019ve made a move and the other side needs to sit with it.",
             "domains": "negotiation, management, dating",
             "how": "Don\u2019t send the follow-up. Let 24-48 hours pass. The silence forces engagement and communicates you\u2019re not anxious."},
            {"name": "The Monday 9am Reopen", "category": "Timing", "risk": "Medium",
             "use_when": "You want to restart a stalled conversation in a professional way.",
             "domains": "sales, partnerships, management",
             "how": "Monday 9am email. \u201cGood morning \u2014 I thought about our Thursday conversation over the weekend and wanted to raise one thing.\u201d The timing signals you took it seriously. The reopen lands clean."},
        ],
    },
    {
        "num": 5,
        "title": "REFRAMING AND FRAME CONTROL",
        "subtitle": "When you can\u2019t win the conversation being had, change what it\u2019s about.",
        "techniques": [
            {"name": "The Cost-of-Inaction Frame", "category": "Reframe", "risk": "Medium",
             "use_when": "The other side is treating doing nothing as free.",
             "domains": "sales, management, family decisions",
             "how": "Quantify what they\u2019re paying for the delay. Not in hypothetical terms. In actual dollars or hours. Inaction stops feeling like a safe choice once it has a price tag.",
             "deploy": "Procurement delaying signoff: \u201cEvery week you wait, your team spends 20 hours on the manual workaround. That\u2019s $3,000 a week we\u2019re burning.\u201d They sign."},
            {"name": "Identity Shift Reframe", "category": "Reframe", "risk": "High",
             "use_when": "The current frame makes them resist and you need a new one.",
             "domains": "leadership, therapy, hard conversations",
             "how": "Shift the frame from role to identity. \u201cYou\u2019re not a manager blocking this; you\u2019re a senior leader deciding strategic priorities.\u201d The reframe gives them a more flattering way to say yes."},
            {"name": "The Bigger Context", "category": "Reframe", "risk": "Low",
             "use_when": "The conversation is stuck on local detail and you want to zoom out.",
             "domains": "strategy, family",
             "how": "Place the current issue in the context of something bigger they care about. \u201cZoom out a year: does this choice move you toward or away from the company you want?\u201d"},
            {"name": "\u201cThe Real Question Is\u2026\u201d", "category": "Reframe", "risk": "Medium",
             "use_when": "They\u2019re focused on the wrong question and you need to redirect.",
             "domains": "negotiation, strategy, management",
             "how": "\u201cThe real question isn\u2019t X. It\u2019s Y.\u201d The phrase is confident enough that the listener usually accepts the redirect. Used carefully it\u2019s reframe; used carelessly it\u2019s manipulation."},
            {"name": "From Price to Value", "category": "Reframe", "risk": "Low",
             "use_when": "A price objection is blocking a decision.",
             "domains": "sales",
             "how": "Move the conversation from price-per-unit to value-over-time. Most price objections are actually value unclear. Make the value unmissable and price becomes secondary."},
            {"name": "The Time Horizon Flip", "category": "Reframe", "risk": "Medium",
             "use_when": "The short-term looks bad and the long-term looks good.",
             "domains": "strategy, investing, career",
             "how": "Shift the time horizon. \u201cOver twelve months, the shape of this looks different.\u201d If the long-term argument is genuinely stronger, the flip works. If you\u2019re using it to dodge a bad short-term reality, it backfires."},
            {"name": "Them as Hero Frame", "category": "Reframe", "risk": "Low",
             "use_when": "You need them to make a hard choice and the choice looks like losing.",
             "domains": "management, sales, family",
             "how": "Frame the decision as heroic. \u201cThis is the call only a real leader can make.\u201d The identity elevation gives them cover to do the right thing."},
            {"name": "The Us-Against-Problem", "category": "Reframe", "risk": "Low",
             "use_when": "The conversation is becoming adversarial.",
             "domains": "partnerships, family, customer conflict",
             "how": "Shift from them-vs-you to us-vs-problem. \u201cWe both want this sorted. What\u2019s the cleanest way?\u201d The adversarial frame dissolves."},
            {"name": "Redefining the Win", "category": "Reframe", "risk": "Medium",
             "use_when": "The current definition of success is wrong or narrow.",
             "domains": "strategy, sales, career",
             "how": "Redefine what winning looks like. \u201cThe real win here isn\u2019t hitting the number; it\u2019s building a repeatable motion.\u201d Done honestly this opens better decisions."},
            {"name": "The Small Compared to What?", "category": "Reframe", "risk": "Medium",
             "use_when": "They think something is expensive, big, or scary.",
             "domains": "sales, management, personal",
             "how": "Anchor the thing against something bigger. \u201c$10K feels big compared to $0. Compared to the $200K of engineering time we\u2019ll save, it\u2019s rounding error.\u201d"},
            {"name": "Frame as Service", "category": "Reframe", "risk": "Low",
             "use_when": "You need to ask for something and want to position it as helping them.",
             "domains": "sales, management, family",
             "how": "Reframe your ask as something that serves their goal. Not manipulatively. Honestly. If it actually does serve them, name the service."},
            {"name": "The Opportunity Cost", "category": "Reframe", "risk": "Medium",
             "use_when": "They\u2019re choosing between two options and treating it as equal.",
             "domains": "strategy, investing, career",
             "how": "Name what they\u2019re giving up by choosing one over the other. Opportunity cost is almost always underweighted. Name it and the decision shifts."},
            {"name": "Reasonable Man Frame", "category": "Reframe", "risk": "Medium",
             "use_when": "You want to pressure a decision without sounding pressuring.",
             "domains": "negotiation, family",
             "how": "\u201cAny reasonable person in your position would\u2026\u201d The frame makes the alternative feel like unreasonableness, which is socially expensive. Use sparingly."},
            {"name": "Category Reframe", "category": "Reframe", "risk": "Medium",
             "use_when": "The thing you\u2019re selling or proposing is being placed in the wrong category.",
             "domains": "sales, strategy, pitching",
             "how": "Move it to a different category. \u201cThis isn\u2019t a tool, it\u2019s an insurance policy.\u201d The category change changes the evaluation criteria."},
            {"name": "Counter-Narrative Plant", "category": "Reframe", "risk": "High",
             "use_when": "A bad narrative is forming and you want to seed a different one.",
             "domains": "politics, internal communications, PR",
             "how": "Introduce a single line of different narrative without attacking the first. Let it sit. Over days or weeks the counter-narrative often displaces the original."},
            {"name": "\u201cWhat If This Isn\u2019t About\u2026?\u201d", "category": "Reframe", "risk": "High",
             "use_when": "The surface conversation is a proxy for something deeper.",
             "domains": "couples, family, management, therapy",
             "how": "\u201cWhat if this actually isn\u2019t about the dishes?\u201d The question invites them to surface the real issue. Used with care."},
            {"name": "The Observer Frame", "category": "Reframe", "risk": "Low",
             "use_when": "Someone is stuck in their own perspective.",
             "domains": "coaching, management, family",
             "how": "\u201cIf you were watching yourself from outside, what would you tell yourself?\u201d The observer perspective unlocks answers the participant perspective can\u2019t reach."},
            {"name": "The Year-From-Now View", "category": "Reframe", "risk": "Low",
             "use_when": "Short-term pressure is driving bad decisions.",
             "domains": "career, strategy, family",
             "how": "\u201cA year from now, which version of this decision do you want to be telling the story about?\u201d The view from the future changes the decision in the present."},
            {"name": "Status Flip", "category": "Reframe", "risk": "High",
             "use_when": "Someone is treating you as low-status and you need to reset.",
             "domains": "sales, dating, management",
             "how": "Do something only a higher-status person would do. Leave first. Disagree calmly. Redirect the conversation. Quiet status moves reset the hierarchy without any display."},
            {"name": "The Permission Reframe", "category": "Reframe", "risk": "Low",
             "use_when": "They\u2019re waiting for someone to give them permission to act.",
             "domains": "management, family",
             "how": "Give them explicit permission for the thing they already wanted to do. \u201cYou don\u2019t need anyone\u2019s permission to do this.\u201d"},
            {"name": "Framing Their Objection As Agreement", "category": "Reframe", "risk": "High",
             "use_when": "They\u2019re raising an objection that, reframed, actually supports your case.",
             "domains": "sales, debate",
             "how": "\u201cYou\u2019re actually making my point.\u201d Then explain why. Must be genuine, or it reads as slippery."},
            {"name": "The Scarcity-to-Plenty Flip", "category": "Reframe", "risk": "Medium",
             "use_when": "Their scarcity mindset is driving a suboptimal decision.",
             "domains": "career, negotiation",
             "how": "Reframe the situation in terms of abundance. \u201cThere isn\u2019t one offer. There are three more in the pipeline. You can walk from this one.\u201d"},
            {"name": "Turning No Into Not-Yet", "category": "Reframe", "risk": "Low",
             "use_when": "You got a no and want to preserve the relationship.",
             "domains": "sales, dating",
             "how": "\u201cUnderstood. Let\u2019s mark this as not-yet, not no.\u201d Re-frames the closure as a pause. 30% of not-yets become yeses within six months."},
            {"name": "\u201cWe\u2019re Actually Aligned\u201d", "category": "Reframe", "risk": "Medium",
             "use_when": "The conversation feels adversarial but you see shared ground.",
             "domains": "all",
             "how": "Name the alignment. \u201cI think we\u2019re actually aligned on the outcome. We disagree on the path.\u201d Often unlocks collaboration."},
            {"name": "The Third Option Reveal", "category": "Reframe", "risk": "Medium",
             "use_when": "A conversation is stuck between two options.",
             "domains": "strategy, family, negotiation",
             "how": "Introduce a third option neither has considered. Almost any stuck binary has a third option. Finding it is the unlock."},
        ],
    },
]
