#!/usr/bin/env python3
"""Vault techniques parts 6-10 (techniques 126-250)."""

PARTS_6_10 = [
    {
        "num": 6,
        "title": "HANDLING OBJECTIONS & PUSHBACK",
        "subtitle": "Most objections are signals, not walls.",
        "techniques": [
            {"name": "The Reverse Echo", "category": "Objection", "risk": "Low",
             "use_when": "They raise an objection and you need a beat to think.",
             "domains": "sales, negotiation, debate",
             "how": "Repeat the objection back as a question. \u201cToo expensive?\u201d The repetition buys you 3-5 seconds and often prompts them to elaborate, revealing the real concern underneath."},
            {"name": "Name-Their-Concern-First", "category": "Objection", "risk": "Low",
             "use_when": "You know an objection is coming.",
             "domains": "sales, internal pitches",
             "how": "Raise it before they do. \u201cYou\u2019re probably worried about integration time.\u201d Addressing it preemptively removes it as a weapon and signals awareness."},
            {"name": "\u201cWhat specifically\u2026\u201d", "category": "Objection", "risk": "Low",
             "use_when": "They raise a vague objection.",
             "domains": "sales, management",
             "how": "Ask for specificity. \u201cWhat specifically about the pricing?\u201d Vague objections are usually covers for real but unspoken concerns. Specificity either surfaces the real concern or collapses the fake one."},
            {"name": "The Paraphrase Check", "category": "Objection", "risk": "Low",
             "use_when": "You want to confirm you understand their objection before responding.",
             "domains": "all",
             "how": "Paraphrase what they said: \u201cSo if I\u2019ve got this right, your concern is X because Y.\u201d They either confirm (now they\u2019ve committed to the framing) or correct (now you know the real concern)."},
            {"name": "Agree-and-Pivot", "category": "Objection", "risk": "Low",
             "use_when": "Their objection is partially valid.",
             "domains": "all",
             "how": "Agree with the valid part, then pivot to the part that matters. \u201cYou\u2019re right that it takes setup. And the setup is one-time; the savings are monthly.\u201d"},
            {"name": "The Partial Concession", "category": "Objection", "risk": "Medium",
             "use_when": "You\u2019ve been asked for something you can\u2019t fully give.",
             "domains": "negotiation, management",
             "how": "Give part of what they asked for, publicly, and name what you can\u2019t. The partial concession builds trust because it shows you\u2019re engaging, not performing refusal."},
            {"name": "Delayed Rebuttal", "category": "Objection", "risk": "Medium",
             "use_when": "You want to let an objection sit before responding.",
             "domains": "debate, negotiation",
             "how": "Let the objection exist for 30-60 seconds before responding. The delay signals you took it seriously. Sometimes during the pause, they soften it themselves."},
            {"name": "The \u201cYes, and\u2026\u201d", "category": "Objection", "risk": "Low",
             "use_when": "You want to acknowledge and build, not argue.",
             "domains": "all",
             "how": "Yes, and\u2026 builds on what they said rather than countering it. Improv rule applied to business conversations."},
            {"name": "Feel-Felt-Found (Modernized)", "category": "Objection", "risk": "Medium",
             "use_when": "You want to show empathy and redirect at once.",
             "domains": "sales, customer service",
             "how": "The classic sales move, updated: \u201cI hear you. I\u2019ve had clients land there and then realize X.\u201d The original is too visibly scripted. The modernized version lands clean."},
            {"name": "The Expected Attack Disarm", "category": "Objection", "risk": "High",
             "use_when": "You know a hostile attack is coming.",
             "domains": "politics, internal disputes",
             "how": "Name the attack before they launch it. \u201cI expect someone\u2019s going to argue that this was sloppy execution. Let me address that.\u201d The attack loses its punch because it\u2019s already in the room."},
            {"name": "Objection as Signal", "category": "Objection", "risk": "Low",
             "use_when": "They object and you want to read the objection as information.",
             "domains": "sales, discovery",
             "how": "Treat the objection as a window into what they care about. \u201cIt sounds like reliability is the critical factor for you. Let\u2019s spend a few minutes on that.\u201d The objection becomes the path forward."},
            {"name": "\u201cYou\u2019re right, but\u2026\u201d", "category": "Objection", "risk": "High",
             "use_when": "You need to acknowledge and still redirect.",
             "domains": "all",
             "how": "The \u201cbut\u201d erases the \u201cyou\u2019re right.\u201d Use \u201cand\u201d instead. \u201cYou\u2019re right, and there\u2019s another angle.\u201d The acknowledgement holds.",
             "counter": "When you hear \u201cyou\u2019re right, but,\u201d they\u2019re about to erase the right. The and version is the real concession."},
            {"name": "The Cost of Your Objection", "category": "Objection", "risk": "Medium",
             "use_when": "Their objection has a cost attached.",
             "domains": "sales, management",
             "how": "Name what their objection is costing them. \u201cIf we go with your approach, we delay launch three weeks.\u201d Objections often feel free; naming the cost changes the calculus."},
            {"name": "Turning Their Complaint Into Criteria", "category": "Objection", "risk": "Medium",
             "use_when": "A complaint can be re-stated as a success criterion.",
             "domains": "sales, product, management",
             "how": "\u201cSo if we solved for that, would you move forward?\u201d Converts a vague gripe into a specific condition you can meet."},
            {"name": "The Acknowledged Fear", "category": "Objection", "risk": "Medium",
             "use_when": "The objection is really a fear.",
             "domains": "sales, leadership, therapy",
             "how": "Name the fear gently. \u201cIt sounds like the real worry is being the person who chose this and being wrong.\u201d The acknowledgement often unlocks the conversation."},
            {"name": "\u201cWhat would make you comfortable?\u201d", "category": "Objection", "risk": "Low",
             "use_when": "You\u2019ve hit a wall and need their solution.",
             "domains": "negotiation, sales, family",
             "how": "Ask them what would solve it. 40% of the time they name something smaller than you were prepared to offer."},
            {"name": "The Hypothetical Removal", "category": "Objection", "risk": "Medium",
             "use_when": "The objection has many layers.",
             "domains": "sales, consulting",
             "how": "\u201cIf the pricing concern went away, what would be next on your list?\u201d Peels the objections one at a time. Reveals whether pricing is real or a proxy."},
            {"name": "Narrow-Then-Answer", "category": "Objection", "risk": "Low",
             "use_when": "A broad objection needs to be addressed.",
             "domains": "all",
             "how": "Narrow the objection to one piece, answer that, then ask if there\u2019s more. \u201cLet me start with the timeline \u2014 that\u2019s the piece you asked about first.\u201d"},
            {"name": "The Detached Response", "category": "Objection", "risk": "Medium",
             "use_when": "You\u2019re attached to the outcome and they know it.",
             "domains": "negotiation, sales",
             "how": "Respond with slight detachment. \u201cCould be. Or could be the opposite.\u201d Detachment disarms pressure."},
            {"name": "Redirect Through Question", "category": "Objection", "risk": "Low",
             "use_when": "You want to redirect without rejecting.",
             "domains": "all",
             "how": "Ask a question that moves the conversation. \u201cFair point \u2014 how does your team usually handle that?\u201d You\u2019ve moved on without dismissing."},
            {"name": "Thank-Then-Clarify", "category": "Objection", "risk": "Low",
             "use_when": "Someone raises a critical objection and you want to honor it.",
             "domains": "management, debate",
             "how": "\u201cThank you for raising that. Let me make sure I understand.\u201d The thank-you buys you permission to push back."},
            {"name": "The Confusing Objection Stall", "category": "Objection", "risk": "High",
             "use_when": "Someone is throwing objections rapid-fire to stall you.",
             "domains": "enterprise sales, political meetings",
             "how": "Stop. \u201cI\u2019ve counted four objections in two minutes. Which one is the real one?\u201d Forces the real objection to surface."},
            {"name": "Let Them Win Small", "category": "Objection", "risk": "Medium",
             "use_when": "You need to concede something to keep the larger point.",
             "domains": "negotiation, couples",
             "how": "Give them a small, real win early in the conversation. It reduces their need to fight for bigger wins later."},
            {"name": "Document the Concern", "category": "Objection", "risk": "Low",
             "use_when": "They raise an objection you can\u2019t solve now.",
             "domains": "sales, consulting",
             "how": "Write it down in front of them. The act of documenting honors the concern and defers it, usually without further argument."},
            {"name": "The \u201cI\u2019ll Come Back to That\u201d", "category": "Objection", "risk": "Low",
             "use_when": "You need to set aside an objection temporarily.",
             "domains": "sales, teaching",
             "how": "\u201cGreat question. I\u2019ll come back to that. Let me finish this part first.\u201d Most of the time they don\u2019t come back to it either."},
        ],
    },
    {
        "num": 7,
        "title": "DEFENSIVE & ANTI-MANIPULATION",
        "subtitle": "Playing the game well also means recognizing when someone else is playing you.",
        "techniques": [
            {"name": "Gaslighting Counter-Document", "category": "Defense", "risk": "Low",
             "use_when": "Someone keeps telling you things didn\u2019t happen that you know did.",
             "domains": "family, management, legal",
             "how": "Document events in writing, with dates, immediately after they happen. When the gaslighting starts, your documents are your anchor. The documentation itself often deters further gaslighting once the other person realizes you\u2019re tracking."},
            {"name": "The Reality Anchor", "category": "Defense", "risk": "Low",
             "use_when": "You\u2019re being pulled into someone else\u2019s distorted version of events.",
             "domains": "family, workplace",
             "how": "Anchor to a single external fact. A text message. A calendar invite. A witness. Don\u2019t argue the narrative; cite the fact."},
            {"name": "DARVO Detection", "category": "Defense", "risk": "Medium",
             "use_when": "You raise a legitimate issue and suddenly you\u2019re the one being accused.",
             "domains": "workplace, family, legal",
             "how": "Name the pattern silently to yourself: Deny, Attack, Reverse Victim and Offender. Don\u2019t defend against the reversal. Return to the original point, calmly. \u201cWe\u2019re not talking about that right now. We\u2019re talking about X.\u201d"},
            {"name": "Love-Bombing Radar", "category": "Defense", "risk": "Low",
             "use_when": "Someone new in your life is being disproportionately generous fast.",
             "domains": "dating, business, religious, multi-level",
             "how": "Trust is earned over time through small consistent acts. When someone delivers big trust inputs fast, the question to ask is what they\u2019re installing trust to extract later."},
            {"name": "The Victim-Claim Test", "category": "Defense", "risk": "Medium",
             "use_when": "Someone keeps positioning themselves as the victim to avoid accountability.",
             "domains": "family, workplace",
             "how": "Notice whether the victim-claim pattern is consistent across different people in their life. If they\u2019re always the victim across multiple unrelated contexts, the pattern is the person, not the situation."},
            {"name": "Anti-Triangulation", "category": "Defense", "risk": "Medium",
             "use_when": "Someone is using a third party to manipulate you.",
             "domains": "family, workplace, dating",
             "how": "\u201cIf this is between you and them, let\u2019s get them in the room.\u201d Most triangulation collapses when the third leg is invited to speak."},
            {"name": "The Calibrated Refusal", "category": "Defense", "risk": "Low",
             "use_when": "You need to say no without damaging the relationship.",
             "domains": "all",
             "how": "\u201cThat\u2019s not going to work for me. Is there a different way I can help?\u201d Refusal + offer. Clean no, open door."},
            {"name": "Grey Rock Response", "category": "Defense", "risk": "Medium",
             "use_when": "Someone is fishing for emotional reactions to feed off.",
             "domains": "family, workplace, divorce",
             "how": "Respond minimally, neutrally, boringly. No emotional content. Over time the manipulator loses interest because the feed is gone."},
            {"name": "The Specific Memory Citation", "category": "Defense", "risk": "Medium",
             "use_when": "Someone distorts a past event.",
             "domains": "family, workplace",
             "how": "Cite specific details they can\u2019t argue. \u201cThe conversation happened Thursday at 3pm in the kitchen. You said X. I said Y. I wrote this down the same day.\u201d Specificity is the enemy of gaslighting."},
            {"name": "Emotional Contagion Block", "category": "Defense", "risk": "Medium",
             "use_when": "Someone is dumping their anxiety on you and you\u2019re starting to feel it.",
             "domains": "family, workplace",
             "how": "Slow your breath, loosen your shoulders, and notice the feeling as theirs, not yours. \u201cYou seem really worried about this.\u201d Naming it as theirs keeps it theirs."},
            {"name": "Boundary Without Anger", "category": "Defense", "risk": "Low",
             "use_when": "You need to set a limit with someone who will escalate if you do it emotionally.",
             "domains": "family, management",
             "how": "State the boundary flat, once, without justification. \u201cI\u2019m not going to discuss this today.\u201d Walk away. No JADE (justify, argue, defend, explain)."},
            {"name": "The Question They Don\u2019t Want Asked", "category": "Defense", "risk": "High",
             "use_when": "Someone is trying to control the frame and you need to break it.",
             "domains": "politics, negotiation, family",
             "how": "Ask the question they\u2019re hoping you won\u2019t. Calmly. In front of whoever is listening. The frame usually collapses."},
            {"name": "Third-Party Reality Check", "category": "Defense", "risk": "Low",
             "use_when": "You\u2019re starting to doubt your own read of a situation.",
             "domains": "all",
             "how": "Describe the situation to a neutral third party and ask if your read seems accurate. Not your friend who will agree. A neutral. Their read is often grounding."},
            {"name": "Screen Record Everything", "category": "Defense", "risk": "Medium",
             "use_when": "You\u2019re in a relationship (personal or professional) where gaslighting is happening.",
             "domains": "workplace, divorce, abuse",
             "how": "Keep records. Emails, screenshots, a written log. You don\u2019t have to use them. You have to have them."},
            {"name": "The Slowdown Under Pressure", "category": "Defense", "risk": "Low",
             "use_when": "Someone is trying to rush you into a decision.",
             "domains": "sales, family, legal",
             "how": "Deliberately slow your responses. \u201cI need to think about this.\u201d Rushed decisions are almost always worse. The person pushing for speed usually knows that."},
            {"name": "\u201cI\u2019ll think about it\u201d Shield", "category": "Defense", "risk": "Low",
             "use_when": "You need to delay without refusing.",
             "domains": "all",
             "how": "\u201cI\u2019ll think about it.\u201d Period. No timeline. No promise. The phrase is a complete sentence and a complete shield."},
            {"name": "Detaching From the Accusation", "category": "Defense", "risk": "Medium",
             "use_when": "You\u2019re being accused of something and your instinct is to defend.",
             "domains": "family, management, legal",
             "how": "Don\u2019t defend. Investigate. \u201cInteresting \u2014 tell me more about what you saw.\u201d Detaching from the accusation removes the energy the accuser was feeding on."},
            {"name": "Writing It Down First", "category": "Defense", "risk": "Low",
             "use_when": "You\u2019re about to have an important conversation and you don\u2019t want to lose your thread.",
             "domains": "all",
             "how": "Write the three things you want to say before the conversation. In the moment, when emotion rises, the written list is your anchor. Manipulators rely on you losing your thread."},
            {"name": "The Witness Frame", "category": "Defense", "risk": "High",
             "use_when": "You\u2019re in a situation where you need someone else present.",
             "domains": "HR, divorce, difficult family",
             "how": "Refuse to have the conversation without a witness. \u201cI\u2019m happy to discuss this with HR present.\u201d If the other person objects to a witness, the witness was the issue."},
            {"name": "Refusing the False Choice", "category": "Defense", "risk": "Medium",
             "use_when": "Someone presents two bad options as if they\u2019re the only two.",
             "domains": "all",
             "how": "\u201cThose aren\u2019t the only two options.\u201d Name a third. Or ask what\u2019s missing from the menu. Almost every binary is manufactured."},
            {"name": "Naming the Tactic Gently", "category": "Defense", "risk": "High",
             "use_when": "You\u2019re comfortable letting the other person know you saw what they did.",
             "domains": "negotiation, management",
             "how": "\u201cThat felt like an attempt to anchor me at $50K. Let\u2019s skip that and talk real numbers.\u201d Direct. No accusation. The tactic stops working."},
            {"name": "Exit the Conversation", "category": "Defense", "risk": "Medium",
             "use_when": "The conversation has become unproductive or unsafe.",
             "domains": "all",
             "how": "\u201cI\u2019m going to step away from this for now. Let\u2019s come back to it on Monday.\u201d Leave. Walking away is a skill, not a failure."},
            {"name": "The 24-Hour Rule on Big Asks", "category": "Defense", "risk": "Low",
             "use_when": "Someone is asking for a significant commitment.",
             "domains": "all",
             "how": "Never say yes to a major commitment in the same meeting it\u2019s asked. \u201cGreat \u2014 let me sit with it overnight and get back to you tomorrow.\u201d The 24 hours reveals whether you were going to regret yes."},
            {"name": "Don\u2019t Explain Your Reasonable Request", "category": "Defense", "risk": "Medium",
             "use_when": "You\u2019ve asked for something reasonable and are being pressed to justify it.",
             "domains": "family, workplace, customer service",
             "how": "Repeat the request. Don\u2019t justify. Justifying a reasonable request invites challenge on the justification. Repeat the request verbatim. Eventually they grant it or name a real reason to refuse."},
            {"name": "The Energy Audit", "category": "Defense", "risk": "Low",
             "use_when": "You\u2019re wondering whether a relationship is good for you.",
             "domains": "personal",
             "how": "Track for two weeks: how you feel 30 minutes after each interaction with them. If the pattern is worse than you walked in, that\u2019s data. Your nervous system is an accurate sensor."},
        ],
    },
    {
        "num": 8,
        "title": "READING THE ROOM",
        "subtitle": "Most of the conversation happens in what isn\u2019t said.",
        "techniques": [
            {"name": "The Baseline Read", "category": "Reading", "risk": "Low",
             "use_when": "You want to detect when someone\u2019s state shifts.",
             "domains": "all",
             "how": "In the first two minutes, notice their baseline: tempo, volume, posture, word choice. Later, deviations from baseline are signal. You can\u2019t spot deviation without first observing the baseline."},
            {"name": "Deviation Spotting", "category": "Reading", "risk": "Low",
             "use_when": "You want to know when a topic matters to someone.",
             "domains": "negotiation, discovery, interviewing",
             "how": "When their baseline deviates on a specific topic (slower, faster, longer pauses, different word choice), that\u2019s the topic that matters. Follow it."},
            {"name": "Micro-Expression Window", "category": "Reading", "risk": "Medium",
             "use_when": "You want to catch fleeting reactions.",
             "domains": "in-person conversations",
             "how": "Micro-expressions last 40-500ms. They usually appear at the moment a word or idea lands. Watch the mouth and eyes immediately after you say something important."},
            {"name": "The Word-Choice Analysis", "category": "Reading", "risk": "Medium",
             "use_when": "You want to diagnose the real concern.",
             "domains": "negotiation, discovery",
             "how": "Notice whether they use \u201cwe,\u201d \u201cI,\u201d \u201cthey,\u201d \u201cyou.\u201d Switches in pronouns usually mark shifts in responsibility, alliance, or emotional distance."},
            {"name": "Physical Tell Detection", "category": "Reading", "risk": "Medium",
             "use_when": "You want to know whether someone is comfortable or not.",
             "domains": "in-person",
             "how": "Watch feet, hands, and breath. Words can lie. The body usually doesn\u2019t. Tight shoulders, foot-tapping, shallow breath \u2014 read them."},
            {"name": "Status Hierarchy Map", "category": "Reading", "risk": "Low",
             "use_when": "You\u2019re walking into a new room.",
             "domains": "organizational",
             "how": "In the first five minutes, notice who defers to whom. Not the org chart \u2014 the actual deference pattern. That\u2019s the real hierarchy."},
            {"name": "The Power Question", "category": "Reading", "risk": "Medium",
             "use_when": "You need to know who the real decision maker is.",
             "domains": "enterprise sales, political",
             "how": "Ask: \u201cWho else will weigh in on this decision?\u201d The specific answer tells you where power actually sits, not where org charts say it does."},
            {"name": "Silence Pattern Reading", "category": "Reading", "risk": "Medium",
             "use_when": "You\u2019re in a group and want to read the power dynamics.",
             "domains": "meetings",
             "how": "Notice who is silent when. Silence during their own expertise topic is avoidance. Silence during someone else\u2019s expertise is respect. Silence after their own statement is invitation for pushback."},
            {"name": "Email Tone Decoder", "category": "Reading", "risk": "Medium",
             "use_when": "An email feels off and you can\u2019t tell why.",
             "domains": "workplace",
             "how": "Compare its tone to their normal emails. Colder? Shorter? More formal? The deviation from their baseline is the signal."},
            {"name": "Energy Drop Detection", "category": "Reading", "risk": "Low",
             "use_when": "You want to catch the moment interest wanes.",
             "domains": "sales, presentations",
             "how": "Watch for energy drops: slower responses, less eye contact, shorter answers. The drop usually coincides with the exact moment you lost them. Recover by asking a question."},
            {"name": "The Avoidance Tell", "category": "Reading", "risk": "Medium",
             "use_when": "You think they\u2019re avoiding a topic.",
             "domains": "negotiation, family, therapy",
             "how": "Name it. \u201cI notice you pivot every time we get near pricing.\u201d The pattern-recognition move often unlocks the avoided topic."},
            {"name": "Compliance Face Reading", "category": "Reading", "risk": "Medium",
             "use_when": "Someone says yes but you\u2019re not sure they mean it.",
             "domains": "sales, management",
             "how": "Watch for the micro-disagreement: pressed lips, slight head shake while saying yes, glance down. These are leaks. Follow up with \u201cyou hesitated a bit \u2014 what\u2019s the concern?\u201d"},
            {"name": "Who-Agrees-With-Whom Analysis", "category": "Reading", "risk": "Low",
             "use_when": "You\u2019re in a multi-party meeting.",
             "domains": "politics, boards",
             "how": "Track who nods or verbally supports whom. After the meeting you have a map of alliances that the formal hierarchy won\u2019t show."},
            {"name": "The Decision-Maker ID", "category": "Reading", "risk": "Low",
             "use_when": "You need to know who actually decides.",
             "domains": "enterprise sales",
             "how": "Watch where the group looks when a decision moment arrives. The eyes turn to the real decision maker even when someone else is talking."},
            {"name": "Coalition Spotting", "category": "Reading", "risk": "Medium",
             "use_when": "You\u2019re entering an org with factions.",
             "domains": "politics, consulting",
             "how": "Notice who always arrives together, leaves together, defends each other. Coalitions aren\u2019t usually in the org chart but they run every decision."},
            {"name": "The Dissenter Detection", "category": "Reading", "risk": "Medium",
             "use_when": "Everyone in a meeting is agreeing and you\u2019re suspicious.",
             "domains": "strategy, all meetings",
             "how": "Watch for the quiet dissenter. Arms crossed, no affirmation, glancing at the door. After the meeting, catch them alone. They have the real objection."},
            {"name": "Pronoun Usage Reading", "category": "Reading", "risk": "Medium",
             "use_when": "You want to know how someone feels about their team or partner.",
             "domains": "all",
             "how": "\u201cWe\u201d vs \u201cthey\u201d vs \u201cI\u201d reveals attachment. Someone who used to say \u201cwe\u201d and now says \u201cthey\u201d has shifted allegiance."},
            {"name": "Tense Shift Alert", "category": "Reading", "risk": "Medium",
             "use_when": "Something in the conversation just changed subtly.",
             "domains": "discovery, negotiation",
             "how": "Watch for tense shifts. Past tense on a current project means they\u2019ve already moved on mentally. Future tense on something supposedly done means it\u2019s not done."},
            {"name": "Certainty Decoding", "category": "Reading", "risk": "Medium",
             "use_when": "You want to calibrate confidence in what someone\u2019s telling you.",
             "domains": "all",
             "how": "Hedges (\u201cI think,\u201d \u201cprobably,\u201d \u201cusually\u201d) indicate low confidence. Overclaims (\u201cdefinitely,\u201d \u201c100%\u201d) in high-stakes areas often indicate the opposite of what they claim."},
            {"name": "Group Consensus Check", "category": "Reading", "risk": "Low",
             "use_when": "You want to know whether the room actually agrees.",
             "domains": "meetings, family",
             "how": "Ask each person individually, going around. The going-around move surfaces private disagreements that public polls hide."},
            {"name": "The Boss\u2019s Boss Shadow", "category": "Reading", "risk": "Medium",
             "use_when": "You\u2019re trying to read the power dynamics of an organization.",
             "domains": "enterprise sales, politics",
             "how": "Every decision in a big org has a boss\u2019s-boss shadow on it. Ask \u201cwhose desk does this ultimately sit on?\u201d Even if the answer is \u201cmine,\u201d watch for the glance upward."},
            {"name": "Reading Missing Information", "category": "Reading", "risk": "Medium",
             "use_when": "You\u2019re being told a story and something feels off.",
             "domains": "all",
             "how": "Notice what\u2019s not being mentioned. A story without mention of cost, team, or downside usually has a cost, team, or downside issue they\u2019re hiding."},
            {"name": "Gift-Giving Patterns", "category": "Reading", "risk": "Low",
             "use_when": "Someone gives you unexpected gifts or favors.",
             "domains": "networking, sales",
             "how": "Notice the pattern. Gifts that are too specific, too expensive, or too early in a relationship are almost always installing reciprocity for a future ask."},
            {"name": "Calendar Priority Reading", "category": "Reading", "risk": "Low",
             "use_when": "You want to know what someone really prioritizes.",
             "domains": "management, sales",
             "how": "Look at their calendar (or ask about their day). People spend time on what they actually prioritize, regardless of what they say they prioritize."},
            {"name": "The Response-Time Signal", "category": "Reading", "risk": "Low",
             "use_when": "You want to read how engaged someone is in an ongoing conversation.",
             "domains": "email, dating, sales",
             "how": "Track their response time as a trend, not individual data points. Increasing response time across a week usually means decreasing interest. Sharp drop in response time means something changed."},
        ],
    },
    {
        "num": 9,
        "title": "CLOSES WITHOUT CLOSING",
        "subtitle": "Every obvious close fires the detector. Here\u2019s what doesn\u2019t.",
        "techniques": [
            {"name": "The Natural Next Step", "category": "Close", "risk": "Low",
             "use_when": "The conversation is reaching a decision point.",
             "domains": "sales, management, family",
             "how": "Describe what would naturally happen next, as if the decision is already made. \u201cThe next step is usually X.\u201d They agree or correct. Either way, progress."},
            {"name": "\u201cIt sounds like\u2026\u201d", "category": "Close", "risk": "Low",
             "use_when": "You want to summarize and close at once.",
             "domains": "sales, coaching, management",
             "how": "\u201cIt sounds like we\u2019re aligned on X, Y, and Z. What\u2019s the right way to move forward?\u201d The summary commits them to the alignment; the question moves them to action."},
            {"name": "The Assumptive Plan", "category": "Close", "risk": "High",
             "use_when": "You\u2019re confident the decision is made and want to make it official.",
             "domains": "sales",
             "how": "Start planning the implementation. \u201cLet me send a kickoff invite for next Tuesday.\u201d If they don\u2019t stop you, the deal is done."},
            {"name": "The Conditional Yes", "category": "Close", "risk": "Low",
             "use_when": "They\u2019re close but one thing is blocking.",
             "domains": "sales, negotiation",
             "how": "\u201cIf I solved X, would you be ready to move forward this week?\u201d The conditional surfaces whether X is real and whether there are hidden blockers."},
            {"name": "Let Them Close You", "category": "Close", "risk": "Medium",
             "use_when": "They\u2019re sophisticated buyers who resist being closed.",
             "domains": "enterprise sales, partnerships",
             "how": "Back off. Let them ask about the next step. The sophisticated buyer will close themselves once you stop pushing."},
            {"name": "The Implementation Question", "category": "Close", "risk": "Low",
             "use_when": "The decision is almost made.",
             "domains": "sales, management",
             "how": "Shift the conversation from whether to how. \u201cHow do you usually roll this out to the team?\u201d The brain starts planning and the decision becomes assumed."},
            {"name": "\u201cWhen should we start?\u201d", "category": "Close", "risk": "High",
             "use_when": "You\u2019re confident and want a date.",
             "domains": "sales",
             "how": "Direct. \u201cWhen do you want to start?\u201d They name a date. The close is done."},
            {"name": "The Logistics Handoff", "category": "Close", "risk": "Low",
             "use_when": "You want to subtly signal it\u2019s done.",
             "domains": "sales",
             "how": "\u201cI\u2019ll loop in our implementation team. Can you send me the main contact on your side?\u201d Names are being exchanged. The deal is closing."},
            {"name": "The Calendar Pull", "category": "Close", "risk": "Medium",
             "use_when": "You want a concrete commitment with a date on it.",
             "domains": "all",
             "how": "\u201cCan we find thirty minutes next Thursday or Friday?\u201d The specificity forces commitment or a clean decline."},
            {"name": "Implementation Detail Focus", "category": "Close", "risk": "Low",
             "use_when": "Macro decision looks stuck but micro decisions aren\u2019t.",
             "domains": "sales, management",
             "how": "Dive into micro-details of implementation. The macro decision gets accepted as a side-effect of engaging with the details."},
            {"name": "The \u201cWho On Your Team?\u201d", "category": "Close", "risk": "Medium",
             "use_when": "You want to make it concrete and commit them.",
             "domains": "enterprise sales, partnerships",
             "how": "\u201cWho on your team would run point on this?\u201d Naming a person commits the deal."},
            {"name": "Normalizing the Path Forward", "category": "Close", "risk": "Low",
             "use_when": "They\u2019re nervous about moving.",
             "domains": "sales, coaching",
             "how": "\u201cMost people at your stage start with the basic plan and upgrade in six months. That\u2019s a perfectly fine way to do it.\u201d Normalizing reduces decision anxiety."},
            {"name": "The Option Walk", "category": "Close", "risk": "Low",
             "use_when": "They\u2019re trying to pick between options.",
             "domains": "sales",
             "how": "Walk them through the options out loud. Most buyers, once the options are walked, pick one. The walk itself is the close."},
            {"name": "Commitment Without Ask", "category": "Close", "risk": "Medium",
             "use_when": "You want a micro-commit.",
             "domains": "all",
             "how": "Say what you\u2019re about to do, not what you need from them. \u201cI\u2019ll send over the contract tomorrow.\u201d If they don\u2019t stop you, they\u2019ve agreed."},
            {"name": "The Stake-In-Ground", "category": "Close", "risk": "High",
             "use_when": "You\u2019ve hit the moment to commit.",
             "domains": "all",
             "how": "\u201cI\u2019m going to put a stake in the ground: we start Oct 3rd.\u201d Direct, confident, final. The other side either meets the commitment or raises a real objection."},
            {"name": "\u201cI\u2019ll send that over by\u2026\u201d", "category": "Close", "risk": "Low",
             "use_when": "You want to create forward motion.",
             "domains": "sales, management",
             "how": "Commit yourself to a deliverable. \u201cI\u2019ll send the contract by end of day tomorrow.\u201d Your commit often triggers their response commit."},
            {"name": "The Resource Offer", "category": "Close", "risk": "Low",
             "use_when": "You want to create ownership before the decision.",
             "domains": "sales, consulting",
             "how": "\u201cLet me share the onboarding doc so you can preview what the first two weeks look like.\u201d They engage with what the \u201cyes\u201d looks like, making it more likely."},
            {"name": "Their Assistant Instead of Them", "category": "Close", "risk": "Medium",
             "use_when": "The decision maker is elusive.",
             "domains": "enterprise sales",
             "how": "Loop in their assistant to schedule. The assistant\u2019s involvement is itself a commitment. The deal becomes harder to back out of."},
            {"name": "The Document Trigger", "category": "Close", "risk": "Medium",
             "use_when": "A contract or agreement exists and you need them to engage with it.",
             "domains": "sales",
             "how": "\u201cI\u2019m sending the docs tonight. Can you loop in legal so we don\u2019t lose time?\u201d The document triggers the next action."},
            {"name": "Moving to Practical Questions", "category": "Close", "risk": "Low",
             "use_when": "The conceptual discussion is done.",
             "domains": "all",
             "how": "Shift to practical: timeline, seats, onboarding. The shift signals the decision is made. Most buyers follow."},
            {"name": "The Small Choice Close", "category": "Close", "risk": "Low",
             "use_when": "They\u2019re indecisive on the big choice.",
             "domains": "sales",
             "how": "Offer a small, trivial choice. \u201cDo you want kickoff Tuesday or Thursday?\u201d The small choice forward-commits the bigger one."},
            {"name": "\u201cDoes this next week work, or\u2026\u201d", "category": "Close", "risk": "Medium",
             "use_when": "Standard two-option close, phrased carefully.",
             "domains": "sales, scheduling",
             "how": "\u201cDoes this next week work, or would two weeks out be better?\u201d The either-or presupposes the decision is made and narrows to timing."},
            {"name": "Action-Verb Confirmation", "category": "Close", "risk": "Low",
             "use_when": "You want to verify forward motion.",
             "domains": "sales, management",
             "how": "End with action verbs, not passive language. \u201cI\u2019ll send. You\u2019ll review. We\u2019ll kick off Tuesday.\u201d Action verbs commit."},
            {"name": "The Prepayment Micro-Step", "category": "Close", "risk": "High",
             "use_when": "You want to cement the decision.",
             "domains": "sales",
             "how": "Suggest a small prepayment or deposit. Any real money commits the decision and dramatically reduces later reversal."},
            {"name": "Default Forward Motion", "category": "Close", "risk": "Low",
             "use_when": "You want momentum without pressure.",
             "domains": "all",
             "how": "Treat forward motion as default. Unless they stop you, you\u2019re moving. \u201cI\u2019m setting up the kickoff for Oct 1 unless I hear otherwise.\u201d"},
        ],
    },
    {
        "num": 10,
        "title": "POST-CONVERSATION LOCK-INS",
        "subtitle": "The last thirty seconds and the next thirty hours matter as much as the conversation itself.",
        "techniques": [
            {"name": "The One-Line Recap Email", "category": "Lock-in", "risk": "Low",
             "use_when": "You need to cement what was agreed.",
             "domains": "all",
             "how": "Send a one-line recap immediately. \u201cConfirming we\u2019re starting Oct 1 with the enterprise tier.\u201d The recap is now documented. Reversal drops from 31% to 4% with this one move."},
            {"name": "Same-Day Follow-Up", "category": "Lock-in", "risk": "Low",
             "use_when": "You just had a meaningful conversation.",
             "domains": "sales, networking, dating",
             "how": "Follow up the same day, briefly. The same-day timing signals attention and continues the momentum."},
            {"name": "The Gratitude Send", "category": "Lock-in", "risk": "Low",
             "use_when": "The other person did something generous (made time, made intros, shared expertise).",
             "domains": "all",
             "how": "Specific thank-you within 24 hours. Specific, not generic. Name the thing they did. It installs reciprocity and memory."},
            {"name": "Document What Was Agreed", "category": "Lock-in", "risk": "Low",
             "use_when": "Verbal agreement needs written form.",
             "domains": "all",
             "how": "Write it down and send it. Prevents 90% of \u201cthat\u2019s not what I meant\u201d reversals."},
            {"name": "The Witness Email", "category": "Lock-in", "risk": "Medium",
             "use_when": "You want the agreement witnessed without making it feel like a trap.",
             "domains": "workplace, legal",
             "how": "Cc a relevant third party on the confirmation email, with a natural reason. The witness is now part of the record."},
            {"name": "\u201cI\u2019m Excited About\u2026\u201d Email", "category": "Lock-in", "risk": "Low",
             "use_when": "You want to reinforce their enthusiasm.",
             "domains": "sales, dating",
             "how": "Send a short \u201cI\u2019m excited about X\u201d email naming the thing they\u2019re getting. Enthusiasm is contagious and reduces buyer\u2019s remorse."},
            {"name": "The Next-Step Calendar Invite", "category": "Lock-in", "risk": "Low",
             "use_when": "The conversation ended with a next meeting.",
             "domains": "all",
             "how": "Send the calendar invite within 60 minutes. The calendar invite cements the commitment."},
            {"name": "Resource Delivery", "category": "Lock-in", "risk": "Low",
             "use_when": "You mentioned something helpful you\u2019d send.",
             "domains": "sales, consulting",
             "how": "Send it within 24 hours. The follow-through builds trust and keeps you top-of-mind."},
            {"name": "Referenced Promise", "category": "Lock-in", "risk": "Medium",
             "use_when": "They made a commitment in conversation.",
             "domains": "management, sales",
             "how": "Reference the commitment in a follow-up. \u201cAs you mentioned, you\u2019ll have the security team review by Friday.\u201d The reference creates accountability without confrontation."},
            {"name": "The 24-Hour Lock", "category": "Lock-in", "risk": "Medium",
             "use_when": "You want to prevent buyer\u2019s remorse.",
             "domains": "sales",
             "how": "Send the next-step deliverable within 24 hours. The faster the deliverable, the less window for reversal."},
            {"name": "Third-Party Mention Email", "category": "Lock-in", "risk": "Low",
             "use_when": "You want to reinforce social proof.",
             "domains": "sales",
             "how": "Reference another client in a similar position who\u2019s succeeding. \u201cBy the way, Acme just hit their Q3 numbers using the same playbook.\u201d"},
            {"name": "The Friend-of-the-Decision", "category": "Lock-in", "risk": "Medium",
             "use_when": "They made a decision and you want to reduce the social cost of sticking with it.",
             "domains": "sales, management",
             "how": "Reinforce the decision as one they\u2019re sharing with peers. \u201cYou\u2019re in good company \u2014 Sarah at Acme made the same call last quarter.\u201d"},
            {"name": "Momentum Question", "category": "Lock-in", "risk": "Low",
             "use_when": "You want to keep the decision moving.",
             "domains": "sales, management",
             "how": "Ask a small implementation question. \u201cBefore we kick off, what day works for the initial training?\u201d Keeps momentum without another full meeting."},
            {"name": "The \u201cWhile You\u2019re In\u2026\u201d", "category": "Lock-in", "risk": "Medium",
             "use_when": "You have a related decision to bundle.",
             "domains": "sales, management",
             "how": "\u201cWhile you\u2019re approving this, the security review for Q2 needs your eye too.\u201d Bundling reduces the cost of the second decision."},
            {"name": "Receipt Before Regret", "category": "Lock-in", "risk": "Low",
             "use_when": "You want to send confirmation in the brief positive window.",
             "domains": "sales, service",
             "how": "Send confirmation within 30 minutes of agreement. The positive emotional state is real and brief. Confirmation during it locks the decision in."},
            {"name": "Contract Friction Removal", "category": "Lock-in", "risk": "Medium",
             "use_when": "A contract is the last step.",
             "domains": "sales",
             "how": "Pre-fill everything. Make the signing one click. Every piece of friction is an opportunity to reconsider."},
            {"name": "The Identity Reinforce", "category": "Lock-in", "risk": "Low",
             "use_when": "You want to confirm the identity they took on by deciding.",
             "domains": "coaching, sales",
             "how": "\u201cYou\u2019re the kind of leader who makes the hard call early.\u201d The identity reinforcement hardens the decision."},
            {"name": "Public Commitment Without Pressure", "category": "Lock-in", "risk": "Medium",
             "use_when": "You want to make the decision public to stabilize it.",
             "domains": "management, sales",
             "how": "Ask casually: \u201cWho else on your team should I sync with about the rollout?\u201d Their answer is a public commitment."},
            {"name": "The Calendar Reminder 7 Days Out", "category": "Lock-in", "risk": "Low",
             "use_when": "You have a scheduled follow-up.",
             "domains": "all",
             "how": "Send a brief reminder 7 days out. \u201cLooking forward to our call next Thursday.\u201d Reduces no-shows by 40%."},
            {"name": "Implementation Check-In", "category": "Lock-in", "risk": "Low",
             "use_when": "Between decision and execution.",
             "domains": "consulting, sales",
             "how": "Check in once, briefly, during implementation. Shows you care about outcome, not just signature."},
            {"name": "The Successful Story Back", "category": "Lock-in", "risk": "Low",
             "use_when": "Post-decision you have a story of success.",
             "domains": "consulting, sales",
             "how": "Share a success story from another client at a comparable stage. Reinforces the decision and lays groundwork for expansion."},
            {"name": "Upgrade Signaling", "category": "Lock-in", "risk": "Medium",
             "use_when": "You want to plant the next yes.",
             "domains": "sales",
             "how": "Mention the next tier casually, no pressure. \u201cMost clients stay on this tier for 6-12 months and then move up when team size grows.\u201d The next decision is pre-seeded."},
            {"name": "The \u201cNext Problem\u201d Conversation", "category": "Lock-in", "risk": "Medium",
             "use_when": "The current problem is solved.",
             "domains": "consulting, sales",
             "how": "\u201cSo that\u2019s handled. What\u2019s the next thing keeping you up at night?\u201d The question opens the next engagement without asking for it."},
            {"name": "Continuity Invitation", "category": "Lock-in", "risk": "Low",
             "use_when": "You want to build the ongoing relationship.",
             "domains": "consulting, sales, coaching",
             "how": "\u201cI\u2019d like to keep checking in monthly. Does that work?\u201d Continuity is rarely declined once the initial decision is good."},
            {"name": "The Relationship Upgrade", "category": "Lock-in", "risk": "Medium",
             "use_when": "The conversation has deepened and you want to mark it.",
             "domains": "personal, long-term business",
             "how": "Acknowledge the shift directly. \u201cThis feels like we moved from vendor to partner.\u201d Naming it makes it real."},
        ],
    },
]
