export type Technique = {
  id: string;
  name: string;
  category: 'Influence' | 'Negotiation' | 'Rapport' | 'Framing' | 'Defense';
  difficulty: 1 | 2 | 3;
  description: string;
  howTo: string[];
  whenToUse: string;
  whenNotToUse: string;
};

export const techniques: Technique[] = [
  { id: 'reciprocity', name: 'Reciprocity', category: 'Influence', difficulty: 1, description: 'Give first to create obligation.', howTo: ['Provide unexpected value upfront.', 'Offer a small, thoughtful concession.', 'Frame your request as a way for them to "return the favor."'], whenToUse: 'To open doors and build goodwill.', whenNotToUse: 'When it could be perceived as a bribe.' },
  { id: 'scarcity-frame', name: 'Scarcity Frame', category: 'Influence', difficulty: 2, description: 'Make it rare to make it valuable.', howTo: ["Emphasize limited availability (time, quantity).", "Highlight unique benefits others don't have.", "Use phrases like 'exclusive offer' or 'last chance.'"], whenToUse: 'To create urgency and drive action.', whenNotToUse: 'When the scarcity is obviously artificial.' },
  { id: 'anchoring', name: 'Anchoring', category: 'Negotiation', difficulty: 2, description: 'Set the reference point before they do.', howTo: ["Make the first offer, even if it's high.", "Start with an extreme number to make your real offer seem reasonable.", "Reference a higher-priced competitor."], whenToUse: 'In any negotiation involving numbers (price, salary, etc.).', whenNotToUse: "When you don't have enough information to set a credible anchor." },
  { id: 'social-proof', name: 'Social Proof', category: 'Influence', difficulty: 1, description: 'Show them everyone else is doing it.', howTo: ["Use testimonials and case studies.", "Mention the number of satisfied customers.", "Refer to popular opinion or trends."], whenToUse: 'To reduce uncertainty and build trust.', whenNotToUse: 'When your audience values being unique and contrarian.' },
  { id: 'void-pull', name: 'The Void Pull', category: 'Rapport', difficulty: 3, description: 'Strategic silence that forces their hand.', howTo: ["Ask a calibrated question.", "Go completely silent and wait for them to speak first.", "Maintain relaxed, open body language during the silence."], whenToUse: 'After you have made a point or asked a key question.', whenNotToUse: 'In the early stages of building rapport, as it can feel aggressive.' },
  { id: 'mirroring', name: 'Mirroring', category: 'Rapport', difficulty: 1, description: 'Match their patterns to build unconscious rapport.', howTo: ["Subtly copy their posture and gestures.", "Use the last 1-3 words they said as a question.", "Match their speech rate and tone."], whenToUse: 'In any one-on-one conversation to build a connection.', whenNotToUse: 'When it becomes obvious and looks like mimicry.' },
  { id: 'frame-control', name: 'Frame Control', category: 'Framing', difficulty: 3, description: 'Whoever sets the frame controls the conversation.', howTo: ["Define the context of the conversation from the start.", "Politely reject their frame and assert your own.", "Act as if your frame is the accepted reality."], whenToUse: 'In high-stakes conversations where the context is everything.', whenNotToUse: 'When collaborating with a trusted partner.' },
  { id: 'door-in-the-face', name: 'Door-in-the-Face', category: 'Negotiation', difficulty: 2, description: 'Ask big first, then ask for what you really want.', howTo: ["Make a large, unreasonable request you expect to be rejected.", "After rejection, immediately make your smaller, real request.", "Frame the second request as a concession."], whenToUse: 'When you need to secure a "yes" on a specific request.', whenNotToUse: 'If a rejection could damage the relationship long-term.' },
  { id: 'labeling', name: 'Labeling', category: 'Rapport', difficulty: 2, description: 'Name their emotion to defuse it.', howTo: ["Start with 'It seems like...' or 'It sounds like...'", "Articulate the emotion you observe.", "Pause and let them respond."], whenToUse: 'To de-escalate negative emotions or build empathy.', whenNotToUse: 'When it could come across as patronizing.' },
  { id: 'tactical-empathy', name: 'Tactical Empathy', category: 'Rapport', difficulty: 2, description: 'Show you understand to lower their guard.', howTo: ["Summarize their perspective and feelings accurately.", "Acknowledge their position without agreeing with it.", "Use phrases like 'I understand why you feel that way.'"], whenToUse: 'In any tense or emotional conversation.', whenNotToUse: 'To manipulate someone into a harmful decision.' },
  { id: 'pattern-interruption', name: 'Pattern Interruption', category: 'Framing', difficulty: 2, description: 'Break their script to create an opening.', howTo: ["Say or do something unexpected.", "Ask a question that doesn't fit the context.", "Shift the environment or topic abruptly."], whenToUse: 'To bypass resistance or get someone to think differently.', whenNotToUse: 'When a predictable process is necessary for trust.' },
  { id: 'emotional-hijacking', name: 'Emotional Hijacking', category: 'Influence', difficulty: 3, description: 'Redirect their emotional state.', howTo: ["Tell a story that evokes a different emotion.", "Use humor to break a negative pattern.", "Shift their focus to a future, more positive outcome."], whenToUse: 'To move someone from an unproductive to a productive state.', whenNotToUse: 'To avoid addressing legitimate negative feelings.' },
  { id: 'contrast-principle', name: 'The Contrast Principle', category: 'Negotiation', difficulty: 1, description: 'Make your offer look good by comparison.', howTo: ["Present a more expensive option first.", "Show a 'before' and 'after' scenario.", "Compare your solution to a much worse alternative."], whenToUse: 'When presenting options or prices.', whenNotToUse: 'When the comparison is misleading or dishonest.' },
  { id: 'commitment-consistency', name: 'Commitment & Consistency', category: 'Influence', difficulty: 2, description: 'Get a small yes to lead to the big yes.', howTo: ["Start with a small, easy request.", "Secure a public or written commitment.", "Frame larger requests as consistent with their past actions."], whenToUse: 'To build momentum and encourage follow-through.', whenNotToUse: 'To trap someone in a decision they regret.' },
  { id: 'authority-positioning', name: 'Authority Positioning', category: 'Framing', difficulty: 1, description: 'Project expertise before you speak.', howTo: ["Reference relevant credentials or experience.", "Use confident, assertive language.", "Dress and act the part."], whenToUse: 'When you need to establish credibility quickly.', whenNotToUse: 'When humility and collaboration are more important.' },
  { id: 'accusation-audit', name: 'The Accusation Audit', category: 'Defense', difficulty: 3, description: 'Name their objections before they do.', howTo: ["List every negative assumption they might have about you.", "Acknowledge these potential negatives upfront.", "This disarms them and makes you seem trustworthy."], whenToUse: 'At the start of a difficult conversation or negotiation.', whenNotToUse: 'When it would introduce negatives they had not considered.' },
  { id: 'reframing', name: 'Reframing', category: 'Framing', difficulty: 2, description: 'Change the meaning by changing the context.', howTo: ["Take their weakness and frame it as a strength.", "Shift the focus from short-term cost to long-term value.", "Change the problem from a threat to an opportunity."], whenToUse: 'To overcome objections and change perspectives.', whenNotToUse: 'To dismiss or invalidate someone\'s real concerns.' },
  { id: 'strategic-vulnerability', name: 'Strategic Vulnerability', category: 'Rapport', difficulty: 2, description: 'Show calculated weakness to build trust.', howTo: ["Admit a small, relatable flaw.", "Share a past mistake and what you learned from it.", "Ask for their advice on a minor issue."], whenToUse: 'To appear more human and disarm their defenses.', whenNotToUse: 'When it could undermine your core authority.' },
  { id: 'the-takeaway', name: 'The Takeaway', category: 'Negotiation', difficulty: 3, description: 'Pull back to make them chase.', howTo: ["Show a willingness to walk away from the deal.", "Suggest that maybe it's not a good fit.", "Remove a feature or benefit from the offer."], whenToUse: 'When you sense they are hesitant but interested.', whenNotToUse: 'If they are not yet convinced of your value.' },
  { id: 'cognitive-overload', name: 'Cognitive Overload', category: 'Influence', difficulty: 3, description: 'Give them too much to process, then offer the easy choice.', howTo: ["Present multiple complex options or data points.", "Speak quickly and use jargon.", "Offer your preferred solution as the simple, clear way out."], whenToUse: 'To guide a decision when faced with indecision.', whenNotToUse: 'When clarity and informed consent are ethically required.' },
];
